"use strict";
const assert=require("assert");
const fs=require("fs");
const path=require("path");
const vm=require("vm");

const context={module:{exports:{}},exports:{},Date,Object,Array,String,Number,Boolean,JSON,Math,Promise};
vm.createContext(context);
vm.runInContext(fs.readFileSync(path.join(__dirname,"logger.js"),"utf8"),context,{filename:"logger.js"});
const core=context.module.exports;
assert(core&&typeof core.createLogger==="function");
assert.equal(typeof context.window,"undefined");
const now=1712345678901,writes=[];
const client={getDeviceId:()=>"node-scalp",log:(table,row)=>{writes.push({table,row});return Promise.resolve(true);}};
const logger=core.createLogger({getSupabase:()=>client,getSymbol:()=>"BTCUSDT",now:()=>now,fromLocal:value=>value+1000});
assert.equal(logger.logActivity("DETECTION_QUALIFIED",{sourceTimeframe:"1m",detectorState:{rankValue:88}}),true);
assert.equal(writes[0].table,"scalp_v1_signals");
const v2Writes=[],v2Logger=core.createLogger({getSupabase:()=>({getDeviceId:()=>"vm-v2",log:async(table,row)=>v2Writes.push({table,row})}),getSymbol:()=>"BTCUSDT",getSignalTable:()=>"scalp_v2_signals",now:()=>now});
assert.equal(v2Logger.logActivity("DETECTION_QUALIFIED",{detectorState:{profile:"V2"}}),true);
assert.equal(v2Writes[0].table,"scalp_v2_signals");
assert.equal(v2Writes[0].row.detector_state.profile,"V2");
assert.equal(writes[0].row.machine_id,"node-scalp");
assert.equal(writes[0].row.event_at,new Date(now).toISOString());
assert.equal(logger.logActivity("UNROUTED_ACTION"),false);
logger.logTrade({trancheId:"L1",symbol:"BTCUSDT",direction:"LONG",createdAt:now-5000,closedAt:now,requestedQty:.1,filledQty:.1,entryPrice:100,closedPrice:101},"TP",.1,100);
assert.equal(writes[1].table,"scalp_trades");
assert.equal(writes[1].row.created_at,new Date(now-4000).toISOString());
assert.equal(writes[1].row.device_id,"node-scalp");
console.log("SCALP logger core tests: PASS");
