"use strict";
const assert=require("assert"),fs=require("fs"),path=require("path"),vm=require("vm");
const repo=path.resolve(__dirname,"..","..");
class MemoryStorage{constructor(seed={}){this.data=new Map(Object.entries(seed));}getItem(key){return this.data.has(key)?this.data.get(key):null;}setItem(key,value){this.data.set(key,String(value));}removeItem(key){this.data.delete(key);}}
class TestEventTarget{constructor(){this.listeners={};}addEventListener(type,fn){(this.listeners[type]||=[]).push(fn);}removeEventListener(type,fn){this.listeners[type]=(this.listeners[type]||[]).filter(item=>item!==fn);}dispatchEvent(event){(this.listeners[event.type]||[]).forEach(fn=>fn.call(this,event));return true;}}
class TestEvent{constructor(type,options={}){this.type=type;this.detail=options.detail;}}
function runtime(){const storage=new MemoryStorage(),context={console,Map,Set,Array,Object,String,Number,Boolean,Date,Promise,JSON,Math,Error,TypeError,EventTarget:TestEventTarget,CustomEvent:TestEvent,setTimeout,clearTimeout,localStorage:storage};context.window=context;context.dispatchEvent=()=>true;context.addEventListener=()=>{};context.removeEventListener=()=>{};vm.createContext(context);for(const file of ["features/scalp/config.js","features/scalp/calculations.js","features/scalp/signal-detector.js","features/scalp/state-machine.js"])vm.runInContext(fs.readFileSync(path.join(repo,file),"utf8"),context,{filename:file});return {context,storage,build:context.__BT001_SCALP_BUILD__};}
function fakeGateway(overrides={}){let position=null;const calls=[];return {calls,isAuthenticated:()=>true,symbol:()=>"BTCUSDT",connection:()=>({streamStatus:"live"}),position:()=>({position}),filters:async()=>({tickSize:.1,stepSize:.001,minQty:.001,minNotional:5,leverage:10,positionMode:"ONE_WAY"}),orders:async()=>({orders:[],algoOrders:[]}),balance:async()=>[{availableBalance:"1000"}],commissionRate:async()=>({makerCommissionRate:.0002,takerCommissionRate:.0004}),reconcile:async()=>({position,orders:{orders:[],algoOrders:[]}}),refreshPosition:async()=>position,submitOrder:async params=>{calls.push(["order",params]);if(params.type==="MARKET"&&!params.reduceOnly){position={symbol:"BTCUSDT",side:params.side==="BUY"?"LONG":"SHORT",qty:Number(params.quantity),avg:100};return {orderId:1,executedQty:params.quantity,avgPrice:"100"};}if(params.type==="MARKET"&&params.reduceOnly){position=null;return {orderId:4};}return {orderId:3};},submitAlgoOrder:async params=>{calls.push(["algo",params]);return {algoId:2};},cancelOrder:async params=>{calls.push(["cancel-order",params]);},cancelAlgoOrder:async params=>{calls.push(["cancel-algo",params]);},queryOrder:async()=>null,...overrides,_setPosition:value=>{position=value;},_position:()=>position};}
function event(direction="LONG",type="CROSS",id="new-1"){return {source:"1m",eventId:id,freshnessKey:id,eventType:type,direction,eventState:type==="CROSS"?"COMMITTED":"CONFIRMED",qualified:true,projected:false,publishedAt:Date.now()+5};}
async function run(){
  const {context,build,storage}=runtime(),calc=build.calculations,C=build.config,cases={};
  assert.equal(C.defaults.direction,"ANY");cases.defaultDirAny=true;
  const gateway=fakeGateway(),engine=new build.ScalpEngine({gateway,storage});engine.guide=100;engine.filters={tickSize:.1,stepSize:.001,minQty:.001,minNotional:5,leverage:10,positionMode:"ONE_WAY"};
  engine.config={...engine.config,lot:"0.100",target:"1",stop:"1",direction:"LONG",source:"1m",entryType:"ANY"};engine.state="ARMED";engine.armedAt=Date.now();
  assert.equal(engine.directionAllowed("LONG"),true);assert.equal(engine.directionAllowed("SHORT"),false);const bearish=event("SHORT","CROSS","bearish");assert.equal(engine.considerEntry(bearish),false);assert.equal(bearish.direction,"SHORT");cases.longOnlyAndNoRelabel=true;
  engine.config.direction="SHORT";assert.equal(engine.directionAllowed("SHORT"),true);assert.equal(engine.directionAllowed("LONG"),false);engine.config.direction="ANY";assert(engine.directionAllowed("LONG")&&engine.directionAllowed("SHORT"));cases.shortAndAnyFiltering=true;
  engine.latestBySource.set("1m",event("LONG","BOUNCE","existing"));const before=engine.generation;engine.updateConfig({direction:"LONG"});assert.equal(engine.generation,before+1);assert(engine.baseline.has("existing"));cases.armedConfigRebases=true;
  const projected={...event("LONG","CROSS","projected"),qualified:false,projected:true,eventState:"PROJECTED"};assert.equal(engine.considerEntry(projected),false);cases.projectedNeverEnters=true;
  const rows=[{time:1,open:99.8,high:100.5,low:99.5,close:100},{time:2,open:100,high:101,low:99.7,close:100.5},{time:3,open:100.1,high:100.8,low:99.95,close:100.3}],snapshotFor=(fast,slow)=>({reliable:true,rows,alignedByPeriod:{9:fast,55:slow}});let liveSnap=snapshotFor([99,99.8,100.1],[100,100,100]),closedSnap=snapshotFor([100.1,100.3,100.5],[99.95,99.98,100]);context.PUBLIC_MARKET_DATA_HUB={getAuthoritativeMaSnapshot:(_tf,options)=>options.includeForming===false?closedSnap:liveSnap};const detector=new build.Detector(),liveCross=detector.evaluateTf("1m",{type:"kline",tf:"1m",closed:false,formingRevision:1},1000);assert.equal(liveCross.event.eventState,"LIVE");assert.equal(liveCross.oppositeCross.eventState,"LIVE");liveSnap=snapshotFor([99,99.8,100.3],[100,100,100]);const committed=detector.evaluateTf("1m",{type:"kline",tf:"1m",closed:false,formingRevision:2},1000+C.signal.crossPersistenceMs["1m"]);assert.equal(committed.event.eventState,"COMMITTED");assert.equal(committed.event.qualified,true);const bounce=new build.Detector().evaluateTf("3m",{type:"kline",tf:"3m",closed:true,closedRevision:9,formingRevision:2},9000);assert.equal(bounce.event.eventType,"BOUNCE");assert.equal(bounce.event.eventState,"CONFIRMED");cases.liveCrossCommitsIntrabarAndBounceWaitsClose=true;
  const long=calc.prices({direction:"LONG",entryPrice:100,qty:1,entryCommission:.04,target:1,stop:1,makerRate:.0002,takerRate:.0004,tickSize:.1}),short=calc.prices({direction:"SHORT",entryPrice:100,qty:1,entryCommission:.04,target:1,stop:1,makerRate:.0002,takerRate:.0004,tickSize:.1});
  const longNet=(long.tp-100)-.04-long.tp*.0002,shortNet=(100-short.tp)-.04-short.tp*.0002,longLoss=(100-long.sl)+.04+long.sl*.0004,shortLoss=(short.sl-100)+.04+short.sl*.0004;
  assert(longNet>=1-1e-9&&shortNet>=1-1e-9);assert(longLoss<=1+1e-9&&shortLoss<=1+1e-9);cases.directionAwareNetAndTickRounding=true;
  const estimated=calc.estimate({direction:"LONG",guide:100,qty:1,target:1,stop:1,rates:{maker:.0002,taker:.0004},filters:{tickSize:.1}}),actual=calc.prices({direction:"LONG",entryPrice:100,qty:1,entryCommission:.1,target:1,stop:1,makerRate:.0002,takerRate:.0004,tickSize:.1});assert.notEqual(estimated.tp,actual.tp);assert.deepEqual(calc.formatOutcome({...estimated,guide:12345.67}),{guide:"12,345.67",tpDelta:"1",slDelta:"1",tpFees:"$0.02",slFees:"$0.04"});cases.actualCommissionAndSummaryFormatting=true;
  const validation=calc.validateArm({config:{lot:"0.000",target:1,stop:1},filters:{stepSize:.001,minQty:.001,minNotional:5},guide:100,balance:[{availableBalance:100}],authenticated:true,streamHealthy:true,sourceReady:true,position:null,ownedOrders:[]});assert(!validation.ok);cases.zeroLotCannotArm=true;
  const execGateway=fakeGateway(),execEngine=new build.ScalpEngine({gateway:execGateway,storage:new MemoryStorage()});execEngine.guide=100;execEngine.filters={tickSize:.1,stepSize:.001,minQty:.001,minNotional:5,leverage:10,positionMode:"ONE_WAY"};execEngine.config={...execEngine.config,lot:"0.100",target:"1",stop:"1",source:"1m",entryType:"ANY",direction:"ANY"};execEngine.state="ARMED";execEngine.armedAt=Date.now()-1;await execEngine.executeEntry(event("LONG","CROSS","execute-1"));assert.equal(execEngine.state,"ACTIVE");assert.equal(execGateway.calls[0][0],"order");assert.equal(execGateway.calls[0][1].type,"MARKET");assert.equal(execGateway.calls[1][0],"algo");assert.equal(execGateway.calls[1][1].type,"STOP_MARKET");assert.equal(execGateway.calls[2][0],"order");assert.equal(execGateway.calls[2][1].type,"LIMIT");cases.marketEntrySlBeforeTp=true;
  const callCount=execGateway.calls.length;execEngine.considerEntry(event("LONG","CROSS","execute-1"));assert.equal(execGateway.calls.length,callCount);cases.duplicateEventNoDuplicateEntry=true;
  const lockedDirection=execEngine.config.direction;execEngine.updateConfig({direction:lockedDirection==="LONG"?"SHORT":"LONG",source:"5m",entryType:"BOUNCE"});assert.equal(execEngine.config.direction,lockedDirection);assert.equal(execEngine.config.source,"1m");assert.equal(execEngine.config.entryType,"ANY");cases.entryFiltersLockedWhileActive=true;
  execEngine.config.direction="LONG";await execEngine.requestExit("OPPOSITE_CROSS",event("SHORT","CROSS","opposite"));assert.equal(execGateway._position(),null);assert.equal(execEngine.state,"OFF");assert(execGateway.calls.some(([kind,params])=>kind==="order"&&params.type==="MARKET"&&params.reduceOnly==="true"));cases.oppositeExitIgnoresDirAndUsesRemaining=true;
  const failedGateway=fakeGateway({submitAlgoOrder:async()=>{throw new Error("SL unavailable");}}),failedEngine=new build.ScalpEngine({gateway:failedGateway,storage:new MemoryStorage()});failedEngine.guide=100;failedEngine.filters={tickSize:.1,stepSize:.001,minQty:.001,minNotional:5,leverage:10,positionMode:"ONE_WAY"};failedEngine.config={...failedEngine.config,lot:"0.100",target:"1",stop:"1"};failedEngine.state="ARMED";let failed=false;try{await failedEngine.executeEntry(event("LONG","CROSS","sl-fail"));}catch(_e){failed=true;}assert(failed);assert.equal(failedGateway._position(),null);cases.slFailureSafeCloses=true;
  const tpGateway=fakeGateway(),baseTpSubmit=tpGateway.submitOrder;tpGateway.submitOrder=async params=>{if(params.type==="LIMIT"){tpGateway.calls.push(["order",params]);throw new Error("TP unavailable");}return baseTpSubmit(params);};const tpEngine=new build.ScalpEngine({gateway:tpGateway,storage:new MemoryStorage()});tpEngine.guide=100;tpEngine.filters={tickSize:.1,stepSize:.001,minQty:.001,minNotional:5,leverage:10,positionMode:"ONE_WAY"};tpEngine.config={...tpEngine.config,lot:"0.100",target:"1",stop:"1"};tpEngine.state="ARMED";await tpEngine.executeEntry(event("LONG","CROSS","tp-fail"));assert.equal(tpEngine.state,"PROTECTION_SUBMITTING");assert.equal(tpGateway.calls.filter(([kind])=>kind==="algo").length,1);assert.equal(tpGateway.calls.filter(([kind,params])=>kind==="order"&&params.type==="LIMIT").length,C.order.tpRetry+1);assert(!tpGateway.calls.some(([kind])=>kind==="cancel-algo"));cases.tpFailureRetainsSlAndRetries=true;
  const partialGateway=fakeGateway(),partialEngine=new build.ScalpEngine({gateway:partialGateway,storage:new MemoryStorage()});partialEngine.filters={tickSize:.1,stepSize:.001,positionMode:"ONE_WAY"};partialEngine.state="ENTRY_SUBMITTED";partialEngine.session={symbol:"BTCUSDT",direction:"LONG",source:"1m",entryClientId:"SCALP-E-PART",tpClientId:"SCALP-T-PART",slClientId:"SCALP-S-PART",eventId:"part",generation:1,filledQty:0,avgEntry:0,entryCommission:4,entryCommissionActual:false,liveQty:.1,target:1,stop:1,mode:"SINGLE"};partialEngine.onOrder({order:{c:"SCALP-E-PART",X:"PARTIALLY_FILLED",z:"0.05",ap:"100",n:"0.01",t:1}});assert.equal(partialEngine.state,"ENTRY_PARTIAL");partialEngine.onOrder({order:{c:"SCALP-E-PART",X:"PARTIALLY_FILLED",z:"0.10",ap:"101",n:"0.02",t:2}});assert.equal(partialEngine.session.entryCommission,.03);assert.equal(partialEngine.session.entryCommissionActual,true);cases.partialMultipleFillsUseActualCommission=true;
  const unknownGateway=fakeGateway(),unknownBase=unknownGateway.submitOrder;let unknownFirst=true;unknownGateway.submitOrder=async params=>{if(unknownFirst&&params.type==="MARKET"&&!params.reduceOnly){unknownFirst=false;unknownGateway.calls.push(["order",params]);unknownGateway._setPosition({symbol:"BTCUSDT",side:"LONG",qty:Number(params.quantity),avg:100});const error=new Error("timeout");error.uncertain=true;throw error;}return unknownBase(params);};unknownGateway.queryOrder=async()=>({orderId:91,status:"FILLED"});const unknownEngine=new build.ScalpEngine({gateway:unknownGateway,storage:new MemoryStorage()});unknownEngine.guide=100;unknownEngine.filters={tickSize:.1,stepSize:.001,minQty:.001,minNotional:5,leverage:10,positionMode:"ONE_WAY"};unknownEngine.config={...unknownEngine.config,lot:"0.100",target:"1",stop:"1"};unknownEngine.state="ARMED";await unknownEngine.executeEntry(event("LONG","CROSS","unknown"));await new Promise(resolve=>setTimeout(resolve,380));assert.equal(unknownGateway.calls.filter(([kind,params])=>kind==="order"&&params.type==="MARKET"&&!params.reduceOnly).length,1);assert.equal(unknownEngine.state,"ACTIVE");cases.unknownEntryReconcilesWithoutDuplicate=true;
  const mismatchGateway=fakeGateway(),mismatchEngine=new build.ScalpEngine({gateway:mismatchGateway,storage:new MemoryStorage()});mismatchEngine.state="ACTIVE";mismatchEngine.session={direction:"LONG",source:"1m",liveQty:.1,entryClientId:"SCALP-E-M",eventId:"m"};mismatchGateway._setPosition({symbol:"BTCUSDT",side:"LONG",qty:.05,avg:100});mismatchEngine.onPosition({current:mismatchGateway._position()});assert.equal(mismatchEngine.state,"POSITION_MISMATCH");cases.manualSizeChangeMismatch=true;
  for(const role of ["TP","SL"]){const fillGateway=fakeGateway(),fillEngine=new build.ScalpEngine({gateway:fillGateway,storage:new MemoryStorage()});fillEngine.state="ACTIVE";fillEngine.session={symbol:"BTCUSDT",direction:"LONG",source:"1m",mode:"SINGLE",eventId:`fill-${role}`,entryClientId:`SCALP-E-${role}`,tpClientId:`SCALP-T-${role}`,slClientId:`SCALP-S-${role}`,tpOrderId:31,slOrderId:32};fillGateway._setPosition(null);fillEngine.onOrder({order:{c:role==="TP"?fillEngine.session.tpClientId:fillEngine.session.slClientId,X:"FILLED"}});await new Promise(resolve=>setTimeout(resolve,0));assert.equal(fillEngine.state,"OFF");assert(fillGateway.calls.some(([kind])=>kind=== (role==="TP"?"cancel-algo":"cancel-order")));}cases.tpAndSlFillsCancelCounterpart=true;
  const raceGateway=fakeGateway(),raceEngine=new build.ScalpEngine({gateway:raceGateway,storage:new MemoryStorage()});raceEngine.filters={tickSize:.1,stepSize:.001,positionMode:"ONE_WAY"};raceEngine.state="ACTIVE";raceEngine.session={symbol:"BTCUSDT",direction:"LONG",source:"1m",mode:"SINGLE",eventId:"race",entryClientId:"SCALP-E-RACE",tpClientId:"SCALP-T-RACE",slClientId:"SCALP-S-RACE",exitClientId:"SCALP-X-RACE",tpOrderId:41,slOrderId:42};await raceEngine.requestExit("OPPOSITE_CROSS",event("SHORT","CROSS","race-cross"));assert.equal(raceEngine.state,"OFF");assert(!raceGateway.calls.some(([kind,params])=>kind==="order"&&params.type==="MARKET"));cases.flatDuringCancelCannotReverse=true;
  const continuousGateway=fakeGateway(),continuousEngine=new build.ScalpEngine({gateway:continuousGateway,storage:new MemoryStorage()});continuousEngine.state="FLAT_RECONCILING";continuousEngine.rearmAfterFlat=true;continuousEngine.config={...continuousEngine.config,cooloffMinutes:0};continuousEngine.session={symbol:"BTCUSDT",direction:"LONG",source:"1m",mode:"CONTINUOUS",tpClientId:"SCALP-T-C",slClientId:"SCALP-S-C",eventId:"c"};await continuousEngine.finishExit("TP");assert.equal(continuousEngine.state,"COOL_OFF");await new Promise(resolve=>setTimeout(resolve,5));assert.equal(continuousEngine.state,"ARMED");assert(continuousEngine.generation>0);cases.continuousCooloffRequiresFreshGeneration=true;
  const uiSource=fs.readFileSync(path.join(repo,"features/scalp/ui.js"),"utf8"),css=fs.readFileSync(path.join(repo,"features/scalp/scalp.css"),"utf8"),html=fs.readFileSync(path.join(repo,"index.html"),"utf8"),main=fs.readFileSync(path.join(repo,"main.js"),"utf8"),signal=fs.readFileSync(path.join(repo,"features/pressure-signal/index.js"),"utf8");
  const controlPositions=["scalpDirectionRow","scalpSource","scalpEntryType","Order behaviour","scalpLot","scalpTarget","scalpStop","scalpMode","scalpCooloffRow","scalp-actions","scalpOutcome"].map(text=>uiSource.indexOf(text));assert(controlPositions.every((value,index)=>index===0||value>controlPositions[index-1]));assert(["n","s","e","w","ne","nw","se","sw"].every(dir=>uiSource.includes(`\"${dir}\"`)));assert(uiSource.includes("calc-module-body scalp-body")&&uiSource.includes("calc-module-resize calc-module-resize-${dir}"));cases.uiOrderResizeScrollSpinner=true;
  assert(html.includes("features/scalp/index.js")&&main.includes("ssscSettingsControlCard")&&main.includes("const oldTop=document.querySelector('.topbar > #ssscDashBtn')")&&uiSource.includes('button.textContent="SCALP"'));assert(!uiSource.slice(uiSource.indexOf("hide(){"),uiSource.indexOf("toggle(){")).includes("engine."));assert(uiSource.includes("uiState.outcomeCollapsed")&&uiSource.includes("captureGeometry"));cases.ssscRelocatedScalpToolbar=true;cases.hideCollapseExecutionIndependent=true;
  assert(signal.includes("bt001:signal-publication")&&signal.includes("getLatestStructuredSignal")&&!uiSource.includes("pressureSignalEntryButton"));cases.sigUsesStructuredPublication=true;
  const detectorSource=fs.readFileSync(path.join(repo,"features/scalp/signal-detector.js"),"utf8"),machineSource=fs.readFileSync(path.join(repo,"features/scalp/state-machine.js"),"utf8");assert(detectorSource.includes('hubUpdate.closed===true')&&detectorSource.includes('state:"PROJECTED"')&&detectorSource.includes("crossPersistenceMs[tf]")&&detectorSource.includes("oppositeCross"));assert(machineSource.includes("getAuthoritativeMaSnapshot(this.config.source")&&!machineSource.includes("getElementById(\"interval\")"));cases.bounceCloseCrossIntrabarAndChartIndependent=true;
  assert(uiSource.includes('className="v13-btn scalp-toolbar-button"')&&uiSource.includes("calc-module-window scalp-window")&&uiSource.includes("calc-module-head scalp-head")&&uiSource.includes("calc-module-binance-actions scalp-actions")&&uiSource.includes("calc-module-status scalp-status")&&uiSource.includes("calc-module-panel scalp-outcome"));assert(!css.includes("var(--accent)")&&!/yellow|#facc15|#f0b90b/i.test(css));cases.calculatorThemeAndToolbarTokens=true;
  assert(uiSource.includes("LIVE EVENT DETECTION")&&uiSource.includes('id="scalpDetection${source}"')&&C.sources.length===4);assert(detectorSource.includes('state:contact?"CONTACT":"APPROACH"')&&detectorSource.includes("classifyTimeframe")&&main.includes("classifyTimeframe"));cases.liveDetectionUsesCanonicalSources=true;
  context.MA_STACK_STRIP={classifyTimeframe:tf=>({maEvent:{ref:"EMA 9 / EMA 55",type:"crossover",dir:1,rank:95},quality:88,source:{type:"hub",path:tf}})};liveSnap=snapshotFor([99,99.8,100.3],[100,100,100]);const ranked=new build.Detector().evaluateTf("5m",{type:"kline",tf:"5m",closed:false,formingRevision:5},12000);assert.equal(ranked.event.rank,"A");assert.equal(ranked.event.rankValue,95);assert.equal(ranked.event.canonicalSource.path,"5m");cases.canonicalRankReusedWithoutSecondEngine=true;
  const unrelatedGateway=fakeGateway(),unrelatedEngine=new build.ScalpEngine({gateway:unrelatedGateway,storage:new MemoryStorage()});unrelatedGateway._setPosition({symbol:"BTCUSDT",side:"LONG",qty:.2,avg:101});await unrelatedEngine.recover();assert.equal(unrelatedEngine.state,"OFF");assert.equal(unrelatedEngine.status,"EXISTING LONG POSITION · SCALP cannot arm");assert.equal(unrelatedEngine.configurationLocked(),false);unrelatedEngine.updateConfig({direction:"SHORT",source:"5m",entryType:"BOUNCE",mode:"CONTINUOUS",lot:"0.200"});assert.equal(unrelatedEngine.config.direction,"SHORT");assert.equal(unrelatedEngine.config.source,"5m");assert.equal(unrelatedEngine.config.mode,"CONTINUOUS");const blockedArm=await unrelatedEngine.arm();assert.equal(blockedArm.ok,false);assert.equal(blockedArm.errors[0],"EXISTING LONG POSITION · SCALP cannot arm");assert.equal(unrelatedGateway.calls.length,0);cases.unrelatedPositionBlocksArmWithoutOwnershipOrWrites=true;
  unrelatedEngine.acceptDetection("5m",{status:"CONFIRMED LONG BOUNCE",event:{...event("LONG","BOUNCE","visible-filtered"),source:"5m",rank:null,rankValue:null}});let detectionRows=unrelatedEngine.snapshot().detections,selectedDetection=detectionRows.find(row=>row.source==="5m");assert.equal(selectedDetection.direction,"LONG");assert.equal(selectedDetection.eventType,"BOUNCE");assert.equal(selectedDetection.rank,null);assert.equal(selectedDetection.eligibility,"BLOCKED BY POSITION");assert.equal(detectionRows.length,4);unrelatedGateway._setPosition(null);unrelatedEngine.onPosition({current:null});assert.equal(unrelatedEngine.state,"OFF");assert.equal(unrelatedEngine.status,"OFF");assert.equal(unrelatedEngine.snapshot().armBlockedByPosition,false);assert.equal(unrelatedEngine.config.direction,"SHORT");selectedDetection=unrelatedEngine.snapshot().detections.find(row=>row.source==="5m");assert.equal(selectedDetection.direction,"LONG");assert.equal(selectedDetection.eligibility,"DIR FILTER");cases.flatClearsWarningAndFiltersDoNotRelabel=true;
  const unrelatedShortGateway=fakeGateway(),unrelatedShortEngine=new build.ScalpEngine({gateway:unrelatedShortGateway,storage:new MemoryStorage()});unrelatedShortGateway._setPosition({symbol:"BTCUSDT",side:"SHORT",qty:.1,avg:99});await unrelatedShortEngine.recover();assert.equal(unrelatedShortEngine.status,"EXISTING SHORT POSITION · SCALP cannot arm");assert.notEqual(unrelatedShortEngine.state,"POSITION_MISMATCH");cases.unrelatedShortIsNotMismatch=true;
  const restartStorage=new MemoryStorage({[C.configKey]:JSON.stringify({...C.defaults,lot:"0.100"})}),restartEngine=new build.ScalpEngine({gateway:fakeGateway(),storage:restartStorage});assert.equal(restartEngine.state,"OFF");cases.restartDoesNotRestoreArmed=true;
  restartEngine.state="ARMED";restartEngine.onPrivateStatus({streamStatus:"disconnected"});assert.equal(restartEngine.state,"OFF");cases.reconnectDoesNotRetainIdleArm=true;
  const recoverySession={symbol:"BTCUSDT",direction:"LONG",source:"1m",eventId:"recover",generation:7,entryClientId:"SCALP-E-R",tpClientId:"SCALP-T-R",slClientId:"SCALP-S-R",exitClientId:"SCALP-X-R",liveQty:.1,avgEntry:100,entryCommission:.004,entryCommissionActual:true,target:1,stop:1,mode:"SINGLE"},recoveryStorage=new MemoryStorage({[C.sessionKey]:JSON.stringify(recoverySession)}),recoveryGateway=fakeGateway();recoveryGateway._setPosition({symbol:"BTCUSDT",side:"LONG",qty:.1,avg:100});const recoveredOrders={orders:[{symbol:"BTCUSDT",clientOrderId:"SCALP-T-R"}],algoOrders:[{symbol:"BTCUSDT",clientAlgoId:"SCALP-S-R"}]};recoveryGateway.orders=async()=>recoveredOrders;recoveryGateway.reconcile=async()=>({orders:recoveredOrders});const recoveryEngine=new build.ScalpEngine({gateway:recoveryGateway,storage:recoveryStorage});await recoveryEngine.recover();assert.equal(recoveryEngine.state,"ACTIVE");assert(recoveryEngine.status.includes("recovered"));cases.restartRecoversUnambiguousActive=true;
  console.log("SCALP tests: PASS",cases);return cases;
}
module.exports=run;if(require.main===module)run().catch(error=>{console.error(error);process.exitCode=1;});
