(() => {
  "use strict";
  const root=window.__BT001_SCALP_BUILD__ ||= {},C=root.config,calc=root.calculations;
  if(!C||!calc)throw new Error("SCALP dependencies must load before UI");
  const q=id=>document.getElementById(id);
  class ScalpUI{
    constructor(engine){this.engine=engine;this.window=null;this.uiState=this.loadState();this.numericUpdateGuard=false;this.boundRender=()=>this.render();}
    loadState(){try{const saved=JSON.parse(localStorage.getItem(C.windowKey)||"{}"),state={};if(saved&&saved.geometry)state.geometry=saved.geometry;if(saved&&saved.collapsed)state.collapsed=true;return state;}catch(_e){return {};}}
    saveState(){try{localStorage.setItem(C.windowKey,JSON.stringify(this.uiState));}catch(_e){}}
    install(){this.installToolbar();this.ensureWindow();this.engine.addEventListener("change",this.boundRender);this.render();return this;}
    installToolbar(){const top=document.querySelector(".topbar");if(!top||q("scalpToolbarBtn"))return;const button=document.createElement("button");button.id="scalpToolbarBtn";button.type="button";button.className="v13-btn scalp-toolbar-button";button.textContent="SCALP";button.title="Show or hide SCALP execution";button.setAttribute("aria-controls","scalpWindow");button.setAttribute("aria-pressed","false");const anchor=q("v13LabBtn")||q("apiKeysBtn")||top.firstElementChild;anchor?anchor.insertAdjacentElement("afterend",button):top.insertAdjacentElement("afterbegin",button);button.addEventListener("click",()=>this.toggle());}
    segment(id,values,labels={}){return `<div class="calc-module-binance-actions scalp-segments" id="${id}">${values.map(value=>`<button type="button" data-value="${value}">${labels[value]||value}</button>`).join("")}</div>`;}
    directionLabel(direction,any="ANY"){const value=String(direction||"").toUpperCase();return value==="LONG"?"L":value==="SHORT"?"S":value==="ANY"?any:value;}
    sourceLabel(source){return String(source||"").toLowerCase();}
    detectionMarkup(){return C.sources.map(source=>`<div class="scalp-detection-row" id="scalpDetection${source}" data-source="${source}"><span class="scalp-detection-source">${this.sourceLabel(source)}</span><span data-field="direction">---</span><span data-field="type">---</span><span data-field="phase">---</span><span data-field="rank">---</span><span data-field="eligibility">SOURCE FILTER</span></div>`).join("");}
    ensureWindow(){
      if(this.window)return this.window;const win=document.createElement("section");win.id="scalpWindow";win.className="calc-module-window scalp-window hidden";win.setAttribute("aria-label","SCALP execution");win.innerHTML=`<header class="calc-module-head scalp-head" id="scalpHead"><div class="calc-module-title scalp-head-title" id="scalpHeadTitle">SCALP | OFF</div><div class="calc-module-actions scalp-head-actions"><button id="scalpCollapse" type="button" title="Collapse">−</button><button id="scalpClose" type="button" title="Hide">×</button></div></header><div class="calc-module-body scalp-body"><div class="calc-module-status scalp-status" id="scalpStatus"></div>
        <section class="calc-module-panel scalp-section scalp-detections" id="scalpLiveEventSection"><div class="calc-module-section-title scalp-section-title">Live Event Detection</div><div class="scalp-detection-head"><span>SRC</span><span>DIR</span><span>EVENT</span><span>PHASE</span><span>RANK</span><span>ELIGIBILITY</span></div>${this.detectionMarkup()}</section>
        <section class="calc-module-panel scalp-section" id="scalpSignalSection"><div class="calc-module-section-title scalp-section-title">CONFIGURATION</div><div class="scalp-section-body"><div class="scalp-row" id="scalpDirectionRow"><div class="scalp-label">DIR</div>${this.segment("scalpDirection",["SHORT","LONG","ANY"],{SHORT:"S",LONG:"L"})}</div><div class="scalp-row"><div class="scalp-label">Signal source</div>${this.segment("scalpSource",C.sources)}</div><div class="scalp-row"><div class="scalp-label">Entry type</div>${this.segment("scalpEntryType",["BOUNCE","CROSS","ANY"])}</div><label class="scalp-row scalp-rank-row" id="scalpMinimumRankRow"><span class="scalp-label">Minimum rank</span><span class="scalp-rank-control"><input id="scalpMinimumRank" type="range" min="0" max="100" step="1" value="0"><output id="scalpMinimumRankValue">0</output></span></label></div></section>
        <section class="calc-module-panel scalp-section" id="scalpTradeValuesSection"><div class="calc-module-section-title scalp-section-title">Trade Values</div><div class="scalp-trade-grid"><div class="scalp-trade-head" aria-hidden="true"><span></span><span>VALUE $</span><span>DELTA</span></div><label class="scalp-trade-row"><span class="scalp-trade-label">Lot size</span><input class="scalp-input" id="scalpLot" type="number" min="0" step="0.001" inputmode="decimal"><span class="scalp-trade-empty" aria-hidden="true"></span></label><label class="scalp-trade-row"><span class="scalp-trade-label">Net target</span><input class="scalp-input" id="scalpTarget" type="number" min="0" step="0.5" inputmode="decimal"><input class="scalp-input scalp-delta-input" id="scalpTpDelta" type="number" min="0" step="1" inputmode="numeric" aria-label="TP delta"></label><label class="scalp-trade-row"><span class="scalp-trade-label">Net SL</span><input class="scalp-input" id="scalpStop" type="number" min="0" step="0.5" inputmode="decimal" title="Intended net stop including estimated fees; Market slippage can exceed this amount"><input class="scalp-input scalp-delta-input" id="scalpSlDelta" type="number" min="0" step="1" inputmode="numeric" aria-label="SL delta"></label></div></section>
        <section class="calc-module-panel scalp-section" id="scalpModeSection"><div class="calc-module-section-title scalp-section-title">Mode and Control</div><div class="scalp-section-body"><div class="scalp-row"><div class="scalp-label">Mode</div>${this.segment("scalpMode",["SINGLE","CONTINUOUS"])}</div><label class="calc-module-row scalp-row scalp-cooloff" id="scalpCooloffRow"><span class="scalp-label">Cool-off (min)</span><input class="scalp-input" id="scalpCooloff" type="number" min="0" step="1"></label><label class="scalp-row" id="scalpAutoTradingRow"><span class="scalp-label">Auto-trading</span><input id="scalpAutoTradingEnabled" type="checkbox"></label><label class="scalp-row" id="scalpAutoEntryRow"><span class="scalp-label">Auto-entry</span><input id="scalpAutoEntryEnabled" type="checkbox"></label><label class="scalp-row" id="scalpMaxConcurrentRow"><span class="scalp-label">Max concurrent auto</span><input class="scalp-input" id="scalpMaxConcurrentAutoPositions" type="number" min="1" step="1"></label><label class="scalp-row" id="scalpMaxDailyAutoLossRow"><span class="scalp-label">Daily auto-loss cap $</span><input class="scalp-input" id="scalpMaxDailyAutoLossUsd" type="number" min="0" step="1"></label><div class="calc-module-status scalp-auto-status" id="scalpAutoStatus"></div><div class="calc-module-binance-actions scalp-actions"><button id="scalpArm" type="button">ARM</button><button id="scalpDisarm" type="button">DISARM</button><button class="danger" id="scalpCloseNow" type="button">CLOSE NOW</button></div><div class="calc-module-status is-warning scalp-error" id="scalpError"></div></div></section><footer class="scalp-footer"><div class="scalp-trade-note" id="scalpFeesLine">Entry fees: --- · SL fees: ---</div><div class="scalp-trade-note" id="scalpEntryCriteria"></div></footer>
        </div>${["n","s","e","w","ne","nw","se","sw"].map(dir=>`<div class="calc-module-resize calc-module-resize-${dir} scalp-resize-handle" data-dir="${dir}"></div>`).join("")}`;document.body.appendChild(win);this.window=win;this.restoreGeometry();this.bind();return win;
    }
    bind(){
      q("scalpClose").addEventListener("click",()=>this.hide());q("scalpCollapse").addEventListener("click",()=>this.toggleCollapse());
      [["scalpDirection","direction"],["scalpSource","source"],["scalpEntryType","entryType"],["scalpMode","mode"]].forEach(([id,key])=>q(id).addEventListener("click",event=>{const button=event.target.closest("button[data-value]");if(button&&!button.disabled)this.engine.updateConfig({[key]:button.dataset.value});}));
      const minimumRank=q("scalpMinimumRank");minimumRank.addEventListener("input",()=>this.engine.updateConfig({minimumRank:minimumRank.value}));minimumRank.addEventListener("change",()=>this.engine.updateConfig({minimumRank:minimumRank.value}));
      [{id:"scalpLot",key:"lot",step:.001,decimals:3},{id:"scalpTarget",key:"target",step:.5,decimals:1,driverKey:"tpDriver",driver:"NET_TARGET"},{id:"scalpTpDelta",key:"tpDelta",step:1,decimals:0,driverKey:"tpDriver",driver:"TP_DELTA"},{id:"scalpStop",key:"stop",step:.5,decimals:1,driverKey:"slDriver",driver:"NET_SL"},{id:"scalpSlDelta",key:"slDelta",step:1,decimals:0,driverKey:"slDriver",driver:"SL_DELTA"}].forEach(meta=>this.bindNumeric(meta));const cooloff=q("scalpCooloff");cooloff.addEventListener("input",()=>this.engine.updateConfig({cooloffMinutes:cooloff.value}));cooloff.addEventListener("change",()=>this.engine.updateConfig({cooloffMinutes:Number(cooloff.value)||0}));
      q("scalpAutoTradingEnabled").addEventListener("change",event=>this.engine.updateConfig({autoTradingEnabled:event.target.checked}));
      q("scalpAutoEntryEnabled").addEventListener("change",event=>this.engine.updateConfig({autoEntryEnabled:event.target.checked}));
      q("scalpMaxConcurrentAutoPositions").addEventListener("change",event=>this.engine.updateConfig({maxConcurrentAutoPositions:Number(event.target.value)||1}));
      q("scalpMaxDailyAutoLossUsd").addEventListener("change",event=>this.engine.updateConfig({maxDailyAutoLossUsd:Number(event.target.value)||0}));
      q("scalpArm").addEventListener("click",async()=>{const result=await this.engine.arm();q("scalpError").textContent=result&&result.ok===false?result.errors.join(" · "):"";});q("scalpDisarm").addEventListener("click",()=>this.engine.disarm());q("scalpCloseNow").addEventListener("click",()=>this.engine.closeNow());this.bindDrag();this.bindResize();
    }
    numericPatch(meta,value){return {...(meta.driverKey?{[meta.driverKey]:meta.driver}:{}),[meta.key]:value};}
    normalizeNumeric(input,meta){if(this.numericUpdateGuard)return;input.value=calc.formatNumeric(input.value,meta.decimals);this.engine.updateConfig(this.numericPatch(meta,input.value));}
    adjustNumeric(input,meta,direction){if(input.disabled||this.numericUpdateGuard)return;input.value=calc.stepNumeric(input.value,meta.step,direction,meta.decimals);this.engine.updateConfig(this.numericPatch(meta,input.value));}
    bindNumeric(meta){const input=q(meta.id);input.addEventListener("input",event=>{if(this.numericUpdateGuard)return;this.engine.updateConfig(this.numericPatch(meta,input.value));if(!event.inputType)this.normalizeNumeric(input,meta);});input.addEventListener("change",()=>this.normalizeNumeric(input,meta));input.addEventListener("blur",()=>this.normalizeNumeric(input,meta));input.addEventListener("wheel",event=>{event.preventDefault();this.adjustNumeric(input,meta,event.deltaY<0?1:-1);},{passive:false});input.addEventListener("keydown",event=>{if(event.key!=="ArrowUp"&&event.key!=="ArrowDown")return;event.preventDefault();this.adjustNumeric(input,meta,event.key==="ArrowUp"?1:-1);});}
    bindDrag(){const head=q("scalpHead"),win=this.window;let start=null;head.addEventListener("pointerdown",event=>{if(event.target.closest("button"))return;const rect=win.getBoundingClientRect();start={x:event.clientX,y:event.clientY,left:rect.left,top:rect.top};head.setPointerCapture(event.pointerId);event.preventDefault();});head.addEventListener("pointermove",event=>{if(!start)return;win.style.left=Math.max(4,Math.min(innerWidth-80,start.left+event.clientX-start.x))+"px";win.style.top=Math.max(4,Math.min(innerHeight-34,start.top+event.clientY-start.y))+"px";});const end=event=>{if(!start)return;start=null;try{head.releasePointerCapture(event.pointerId);}catch(_e){}this.captureGeometry();};head.addEventListener("pointerup",end);head.addEventListener("pointercancel",end);}
    bindResize(){this.window.querySelectorAll(".scalp-resize-handle").forEach(handle=>handle.addEventListener("pointerdown",event=>{if(this.window.classList.contains("is-collapsed"))return;const rect=this.window.getBoundingClientRect(),dir=handle.dataset.dir,start={x:event.clientX,y:event.clientY,left:rect.left,top:rect.top,width:rect.width,height:rect.height};event.preventDefault();event.stopPropagation();const move=e=>{const dx=e.clientX-start.x,dy=e.clientY-start.y;let left=start.left,top=start.top,width=start.width,height=start.height;if(dir.includes("e"))width+=dx;if(dir.includes("s"))height+=dy;if(dir.includes("w")){width-=dx;left+=dx;}if(dir.includes("n")){height-=dy;top+=dy;}if(width<C.ui.minWidth){if(dir.includes("w"))left-=C.ui.minWidth-width;width=C.ui.minWidth;}if(height<C.ui.minHeight){if(dir.includes("n"))top-=C.ui.minHeight-height;height=C.ui.minHeight;}left=Math.max(4,Math.min(innerWidth-80,left));top=Math.max(4,Math.min(innerHeight-40,top));width=Math.min(width,innerWidth-left-4);height=Math.min(height,innerHeight-top-4);Object.assign(this.window.style,{left:left+"px",top:top+"px",width:width+"px",height:height+"px"});};const up=()=>{document.removeEventListener("pointermove",move,true);document.removeEventListener("pointerup",up,true);this.captureGeometry();};document.addEventListener("pointermove",move,true);document.addEventListener("pointerup",up,true);}));}
    captureGeometry(){if(this.window.classList.contains("is-collapsed"))return;const r=this.window.getBoundingClientRect();this.uiState.geometry={left:r.left,top:r.top,width:r.width,height:r.height};this.saveState();}
    restoreGeometry(){const g=this.uiState.geometry||{};Object.assign(this.window.style,{left:Math.max(4,Math.min(innerWidth-80,Number(g.left)||90))+"px",top:Math.max(4,Math.min(innerHeight-40,Number(g.top)||70))+"px",width:Math.max(C.ui.minWidth,Number(g.width)||C.ui.defaultWidth)+"px",height:Math.max(C.ui.minHeight,Number(g.height)||C.ui.defaultHeight)+"px"});if(this.uiState.collapsed)this.window.classList.add("is-collapsed");}
    toggleCollapse(){if(!this.window.classList.contains("is-collapsed"))this.captureGeometry();this.uiState.collapsed=!this.window.classList.contains("is-collapsed");this.window.classList.toggle("is-collapsed",this.uiState.collapsed);this.saveState();this.render();}
    syncToolbar(snap=this.engine.snapshot()){const button=q("scalpToolbarBtn");if(!button)return;const open=!this.window.classList.contains("hidden");button.setAttribute("aria-pressed",String(open));button.classList.toggle("is-window-open",open);button.classList.toggle("is-armed",snap.state==="ARMED");button.classList.toggle("is-executing",snap.active);button.classList.toggle("is-error",snap.state==="ERROR"||snap.state==="POSITION_MISMATCH");button.disabled=snap.state==="ERROR"&&!!snap.session;button.title=`SCALP · ${snap.state} · ${open?"window open":"window closed"}`;}
    show(){this.window.classList.remove("hidden");this.render();}hide(){this.window.classList.add("hidden");this.syncToolbar();}toggle(){this.window.classList.contains("hidden")?this.show():this.hide();}
    setSegment(id,value,disabled){q(id).querySelectorAll("button").forEach(button=>{button.classList.toggle("is-active",button.dataset.value===String(value));button.disabled=disabled;});}
    statusText(snap){const status=String(snap.status||"").trim(),quiet=snap.state==="OFF"&&!snap.armBlockedByPosition&&["","IDLE","OFF","DISARMED"].includes(status.toUpperCase());return quiet?"":status;}
    criteriaText(cfg){const direction=this.directionLabel(cfg.direction,"ANY"),source=this.sourceLabel(cfg.source),type=String(cfg.entryType||"ANY").toUpperCase(),rule=type==="BOUNCE"?"confirmed 9/55 bounce at candle close":type==="CROSS"?"actual 9/55 cross":"actual 9/55 cross or confirmed bounce at candle close",minimum=Number(cfg.minimumRank)||0,rank=minimum?`rank ≥ ${minimum}`:"rank OFF";return `Entry criteria: ${source} ${rule} · DIR ${direction} · ${rank}`;}
    rankBreakdownTitle(row){
      const diag=row.rankDiagnostics;if(row.rankValue==null)return "";
      if(!diag)return `Rank: ${row.rankValue}`;
      const ema=`EMA geometry ${Math.round(diag.emaScore)} (70%)`,pressure=diag.pressureAvailable?`Pressure/volume ${Math.round(diag.pressureScore)} (30%)`:"Pressure/volume unavailable";
      return `Rank: ${row.rankValue} — ${ema} · ${pressure}`;
    }
    renderDetections(rows=[]){for(const row of rows){const el=q(`scalpDetection${row.source}`);if(!el)continue;el.classList.toggle("is-selected",!!row.selected);el.dataset.eligibility=row.eligibility||"";const value=(field,text)=>{const normalized=String(text||"").toUpperCase();if(!normalized||normalized==="NONE"||normalized==="—")return "---";return field==="direction"?this.directionLabel(text,"---"):text;},set=(field,text)=>{const node=el.querySelector(`[data-field="${field}"]`);if(node)node.textContent=value(field,text);};el.querySelector(".scalp-detection-source").textContent=this.sourceLabel(row.source);set("direction",row.direction);set("type",row.eventType);set("phase",row.phase);set("rank",row.rankValue==null?null:String(row.rankValue));const rankNode=el.querySelector('[data-field="rank"]');if(rankNode)rankNode.title=this.rankBreakdownTitle(row);set("eligibility",row.eligibility==="BLOCKED BY POSITION"?"BLOCKED":row.eligibility||"NOT CONFIRMED");}}
    render(){
      const snap=this.engine.snapshot(),cfg=snap.config,locked=snap.locked,session=snap.session;q("scalpStatus").textContent=this.statusText(snap);q("scalpStatus").classList.toggle("is-warning",snap.state==="ERROR"||snap.state==="POSITION_MISMATCH"||snap.armBlockedByPosition);q("scalpStatus").dataset.state=snap.state;this.renderDetections(snap.detections);
      let header=`SCALP | ${snap.state}`;if(snap.state==="ARMED")header+=` · ${this.directionLabel(cfg.direction)} · ${cfg.source} · ${cfg.entryType}`;else if(session&&["ACTIVE","PROTECTION_SUBMITTING"].includes(snap.state))header+=` · ${this.directionLabel(session.direction)}`;else if(snap.state==="COOL_OFF")header+=` · ${cfg.cooloffMinutes}m`;q("scalpHeadTitle").textContent=header;q("scalpCollapse").textContent=this.window.classList.contains("is-collapsed")?"+":"−";
      this.setSegment("scalpDirection",cfg.direction,locked);this.setSegment("scalpSource",cfg.source,locked);this.setSegment("scalpEntryType",cfg.entryType,locked);this.setSegment("scalpMode",cfg.mode,locked);q("scalpCooloffRow").classList.toggle("hidden",cfg.mode!=="CONTINUOUS");
      const minimumRank=q("scalpMinimumRank"),minimumValue=Number(cfg.minimumRank)||0;minimumRank.disabled=locked;if(document.activeElement!==minimumRank)minimumRank.value=String(minimumValue);q("scalpMinimumRankValue").textContent=`${minimumValue}`;
      this.numericUpdateGuard=true;[["scalpLot",calc.formatNumeric(cfg.lot,3)],["scalpTarget",calc.formatNumeric(cfg.target,1)],["scalpTpDelta",calc.formatNumeric(cfg.tpDelta,0)],["scalpStop",calc.formatNumeric(cfg.stop,1)],["scalpSlDelta",calc.formatNumeric(cfg.slDelta,0)],["scalpCooloff",cfg.cooloffMinutes]].forEach(([id,value])=>{const input=q(id);input.disabled=locked;if(document.activeElement!==input)input.value=value;});this.numericUpdateGuard=false;q("scalpArm").disabled=snap.armBlockedByPosition||(snap.state!=="OFF"&&snap.state!=="ERROR");q("scalpDisarm").disabled=snap.state==="OFF";const closeNow=q("scalpCloseNow"),actions=closeNow.parentElement;closeNow.style.display=session?"":"none";actions.classList.toggle("has-close",!!session);
      const outcome=snap.outcome||{available:false,reason:"WAITING FOR MARKET DATA"},money=value=>Number.isFinite(Number(value))?`$${Number(value).toFixed(2)}`:"---";q("scalpFeesLine").textContent=outcome.available?`Entry fees: ${money(outcome.entryFee)} · SL fees: ${money(outcome.slFee)}`:"Entry fees: --- · SL fees: ---";q("scalpEntryCriteria").textContent=this.criteriaText(cfg);
      const auto=snap.autoTrading||{},autoTradingInput=q("scalpAutoTradingEnabled"),autoEntryInput=q("scalpAutoEntryEnabled"),maxConcurrentInput=q("scalpMaxConcurrentAutoPositions"),maxLossInput=q("scalpMaxDailyAutoLossUsd");
      if(document.activeElement!==autoTradingInput)autoTradingInput.checked=!!auto.enabled;if(document.activeElement!==autoEntryInput)autoEntryInput.checked=!!auto.autoEntryEnabled;
      if(document.activeElement!==maxConcurrentInput)maxConcurrentInput.value=String(cfg.maxConcurrentAutoPositions??1);if(document.activeElement!==maxLossInput)maxLossInput.value=String(cfg.maxDailyAutoLossUsd??0);
      const autoStatusParts=[auto.enabled?`AUTO-TRADING ON · AUTO-ENTRY ${auto.autoEntryEnabled?"ON":"OFF"}`:"AUTO-TRADING OFF"];
      if(auto.disabledReason)autoStatusParts.push(auto.disabledReason);else if(auto.enabled&&auto.blockedReason)autoStatusParts.push(auto.blockedReason);
      if(auto.dailyLoss)autoStatusParts.push(`Daily auto loss $${Number(auto.dailyLoss.accumulatedUsd||0).toFixed(2)} / cap $${Number(auto.dailyLoss.capUsd||0).toFixed(2)}`);
      const autoStatus=q("scalpAutoStatus");autoStatus.textContent=autoStatusParts.join(" · ");autoStatus.classList.toggle("is-warning",!!auto.disabledReason);
      this.syncToolbar(snap);
    }
    destroy(){this.engine.removeEventListener("change",this.boundRender);this.window&&this.window.remove();q("scalpToolbarBtn")?.remove();}
  }
  root.ScalpUI=ScalpUI;
})();
