(() => {
  "use strict";

  const VERSION="1.0.0";
  const SIGNAL_ID="signal-c";
  const CORE_TIMEFRAMES=Object.freeze(["5m","15m","30m","1h"]);
  const DEPTHS=Object.freeze({"5m":596,"15m":320,"30m":320,"1h":320});
  const PHASES=Object.freeze(["NO EVENT","APPROACH","CONTACT / COLLISION","BOUNCE FORMING","BOUNCE CONFIRMED","CROSS POSSIBLE ON CLOSE","CROSS FORMING","CROSS CONFIRMED","RETEST / HOLD","FAILED / INVALIDATED","EXTENDED / NO CHASE","STALE / UNAVAILABLE"]);
  const ALERT_PHASES=new Set(["APPROACH","CONTACT / COLLISION","BOUNCE CONFIRMED","CROSS POSSIBLE ON CLOSE","CROSS CONFIRMED","RETEST / HOLD","FAILED / INVALIDATED"]);
  const CONFIG=Object.freeze({
    emaFastPeriod:9,emaSlowPeriod:55,emaSecondaryPeriod:21,emaStructuralPeriods:Object.freeze([100,200]),atrPeriod:14,
    minimumRows:70,interactionBandAtr:.12,approachBandAtr:.65,minimumContractionAtr:.018,minimumExpansionAtr:.025,
    meaningfulSlowSlopeAtr:.018,bounceLookbackBars:5,bounceConfirmSeparationAtr:.20,crossFailureBars:4,crossHoldBars:2,extendedEventPersistenceBars:12,
    responseProgressAtr:.22,failureProgressAtr:-.12,chaseDistanceAtr:1.8,eventWindowBars:6,participationBaselineBars:30,
    weakParticipationRatio:.82,strongParticipationRatio:1.12,effectiveProgressAtr:.32,absorptionProgressAtr:.12,
    minimumDirectionalShare:.52,absorptionDirectionalShare:.55,minimumQualifiedResponseScore:60,consecutiveSynchronizationMinimum:3,
    uncontrolledRangeAtr:2.2,forecastPossibleScore:58,forecastFormingScore:42,forecastFreshnessBars:1,
    synchronizationFreshness:Object.freeze({"5m":6,"15m":4,"30m":3,"1h":2}),
    horizonWeights:Object.freeze({quick:Object.freeze({lead:18,intermediate:10,broad:7}),"2_3h":Object.freeze({lead:10,intermediate:18,broad:10}),"6_8h":Object.freeze({lead:6,intermediate:20,broad:18})}),
    gradeBands:Object.freeze({A:80,B:70,C:60})
  });
  const PRESENTATION=Object.freeze({
    "NO SETUP":Object.freeze({tone:"gray",definition:"No authoritative 15m EMA9/EMA55 event is currently available."}),
    WATCHING:Object.freeze({tone:"gray",definition:"A 9/55 interaction is approaching, but the authoritative 15m event is not actionable."}),
    "STAND BY":Object.freeze({tone:"orange",definition:"The authoritative 15m 9/55 interaction needs a closed reaction or hold."}),
    "TRIGGER FORMING":Object.freeze({tone:"orange",definition:"The 15m 9/55 event is developing; closed-candle confirmation remains incomplete."}),
    "TRIGGER ACTIVE":Object.freeze({tone:"green",definition:"The authoritative 15m 9/55 event has a qualified closed reaction and follow-through."}),
    "SETUP FAILED":Object.freeze({tone:"red",definition:"The selected 15m 9/55 event failed or was invalidated."}),
    "NO CHASE":Object.freeze({tone:"red",definition:"The 15m 9/55 move is too extended from its interaction or invalidation area."})
  });

  const num=value=>value==null||value===""?null:(Number.isFinite(Number(value))?Number(value):null);
  const clamp=(value,min=0,max=100)=>Math.max(min,Math.min(max,Number(value)||0));
  const average=values=>{const valid=values.filter(Number.isFinite);return valid.length?valid.reduce((sum,value)=>sum+value,0)/valid.length:null;};
  const unique=values=>[...new Set(values.filter(Boolean))];
  const sideValue=direction=>direction==="LONG"?1:direction==="SHORT"?-1:0;
  const directionForSide=side=>side>0?"LONG":side<0?"SHORT":null;
  const closedRows=(snapshot,tf)=>(snapshot&&snapshot.closedByTf&&snapshot.closedByTf[tf]||[]).filter(row=>row&&row.final!==false&&num(row.close)!=null);
  const liveRows=(snapshot,tf)=>snapshot&&snapshot.rowsByTf&&snapshot.rowsByTf[tf]||closedRows(snapshot,tf);
  function emaSeries(rows,period){
    const alpha=2/(period+1);let prior=null;
    return rows.map(row=>{const close=num(row&&row.close);if(close==null)return prior;prior=prior==null?close:alpha*close+(1-alpha)*prior;return prior;});
  }
  function atr(rows,period=CONFIG.atrPeriod){
    if(rows.length<2)return null;const ranges=[];
    for(let index=Math.max(1,rows.length-period);index<rows.length;index+=1){const row=rows[index],previous=rows[index-1],high=num(row.high),low=num(row.low),priorClose=num(previous.close);if(high==null||low==null||priorClose==null)continue;ranges.push(Math.max(high-low,Math.abs(high-priorClose),Math.abs(low-priorClose)));}
    return average(ranges);
  }
  function slope(series,lookback=3){if(series.length<=lookback)return 0;return (series.at(-1)-series.at(-(lookback+1)))/lookback;}
  function acceleration(series){if(series.length<4)return 0;const latest=series.at(-1)-series.at(-2),prior=series.at(-2)-series.at(-3);return latest-prior;}
  function grade(score){if(!Number.isFinite(score))return "UNAVAILABLE";return score>=CONFIG.gradeBands.A?"A":score>=CONFIG.gradeBands.B?"B":score>=CONFIG.gradeBands.C?"C":"UNACCEPTABLE";}
  function crossClosePrice(previousEMA9,previousEMA55){
    const alpha9=2/(CONFIG.emaFastPeriod+1),alpha55=2/(CONFIG.emaSlowPeriod+1);
    return (((1-alpha55)*previousEMA55)-((1-alpha9)*previousEMA9))/(alpha9-alpha55);
  }
  function flowEvidence(rows,direction,rangeAtr){
    const side=sideValue(direction),window=rows.slice(-CONFIG.eventWindowBars),baseline=rows.slice(-CONFIG.participationBaselineBars-CONFIG.eventWindowBars,-CONFIG.eventWindowBars),volumes=window.map(row=>num(row.volume)||0),baselineVolumes=baseline.map(row=>num(row.volume)||0),volume=average(volumes)||0,baselineVolume=average(baselineVolumes)||volume||1,participationRatio=volume/Math.max(baselineVolume,1e-9);
    const start=num(window[0]&&window[0].open),finish=num(window.at(-1)&&window.at(-1).close),progressAtr=start==null||finish==null||!(rangeAtr>0)?0:(finish-start)*side/rangeAtr;
    const directionalShares=window.map(row=>{const total=num(row.volume),buy=num(row.takerBuyBase);if(!(total>0)||buy==null)return null;return direction==="LONG"?buy/total:(total-buy)/total;}).filter(Number.isFinite),directionalShare=average(directionalShares),ranges=window.map(row=>{const high=num(row.high),low=num(row.low);return high==null||low==null||!(rangeAtr>0)?null:(high-low)/rangeAtr;}).filter(Number.isFinite),rangeRatio=average(ranges);
    const priceProgressPerVolume=progressAtr/Math.max(participationRatio,.05),highVolumeNoProgress=participationRatio>=CONFIG.strongParticipationRatio&&Math.abs(progressAtr)<CONFIG.absorptionProgressAtr,effective=progressAtr>=CONFIG.effectiveProgressAtr&&participationRatio>=CONFIG.weakParticipationRatio&&(directionalShare==null||directionalShare>=CONFIG.minimumDirectionalShare),absorption=highVolumeNoProgress&&directionalShare!=null&&directionalShare>=CONFIG.absorptionDirectionalShare,uncontrolled=(rangeRatio||0)>=CONFIG.uncontrolledRangeAtr&&!effective;
    const score=clamp(45+Math.max(-20,Math.min(25,progressAtr*35))+Math.max(-15,Math.min(18,(participationRatio-1)*35))+(effective?15:0)-(highVolumeNoProgress&&!absorption?18:0)-(uncontrolled?18:0));
    return {score,effective,absorption,highVolumeNoProgress,uncontrolled,participationRatio,progressAtr,directionalShare,rangeRatio,priceProgressPerVolume,evidence:unique([`Event-window participation ${participationRatio.toFixed(2)}x baseline`,`Directional progress ${progressAtr.toFixed(2)} ATR`,directionalShare==null?"Directional volume unavailable":`Directional volume share ${(directionalShare*100).toFixed(0)}%`,highVolumeNoProgress?"High volume produced little directional progress":null,absorption?"Interaction shows directional absorption/rejection":null,uncontrolled?"Range expansion is uncontrolled":null])};
  }
  function crossForecast(snapshot,tf,rows,ema9,ema55,rangeAtr,gapVelocity,fastSlope,slowSlope,fastAcceleration,slowAcceleration,flow){
    if(tf!=="15m"||rows.length<2||!(rangeAtr>0))return null;
    const previousEMA9=ema9.at(-1),previousEMA55=ema55.at(-1),requiredClose=crossClosePrice(previousEMA9,previousEMA55),direction=previousEMA9<previousEMA55?"LONG":previousEMA9>previousEMA55?"SHORT":null,live=liveRows(snapshot,tf),forming=live.findLast?live.findLast(row=>row&&row.final===false):[...live].reverse().find(row=>row&&row.final===false),currentPrice=num(forming&&forming.close)??num(snapshot&&snapshot.currentPrice)??num(rows.at(-1)&&rows.at(-1).close);
    if(!forming||!direction||currentPrice==null||!Number.isFinite(requiredClose))return null;
    const side=sideValue(direction),signedDistance=(requiredClose-currentPrice)*side,distancePrice=Math.abs(requiredClose-currentPrice),distanceAtr=distancePrice/rangeAtr,distanceBps=distancePrice/Math.max(Math.abs(currentPrice),1)*10000,thresholdMet=(currentPrice-requiredClose)*side>=0,closeTime=num(forming&&forming.closeTime),now=num(snapshot&&snapshot.createdAt)??Date.now(),timeRemainingMs=closeTime==null?null:Math.max(0,closeTime-now);
    const gapScore=clamp(100-distanceAtr*120),velocityScore=clamp(50+gapVelocity*250),slopeScore=clamp(50+(fastSlope-slowSlope)*side/rangeAtr*450),accelerationScore=clamp(50+(fastAcceleration-slowAcceleration)*side/rangeAtr*700),participationScore=(flow&&flow.score)??50,timeScore=timeRemainingMs==null?50:clamp(100-timeRemainingMs/(15*60*1000)*45),candleProgressScore=thresholdMet?92:clamp(75-distanceAtr*80),likelihoodScore=Math.round(clamp(gapScore*.25+velocityScore*.18+slopeScore*.16+accelerationScore*.10+participationScore*.14+timeScore*.07+candleProgressScore*.10));
    return {direction,requiredClose,currentPrice,distancePrice,distanceBps,distanceAtr,signedDistance,timeRemainingMs,thresholdMet,likelihoodScore,label:"Explainable cross-likelihood score (uncalibrated)",components:{gapScore,velocityScore,slopeScore,accelerationScore,participationScore,timeScore,candleProgressScore},supporting:unique([gapVelocity>0?"EMA gap is closing":null,thresholdMet?"Current 15m price is beyond the required close":null,flow&&flow.effective?"Event-window flow is effective":null]),opposing:unique([gapVelocity<=0?"EMA gap is not closing":null,!thresholdMet?`15m close still needs ${distancePrice.toFixed(4)} (${distanceBps.toFixed(1)} bps)`:null,flow&&flow.highVolumeNoProgress?"High volume lacks directional progress":null])};
  }
  function analyzeTimeframe(snapshot,tf){
    const rows=closedRows(snapshot,tf),freshness=String(snapshot&&snapshot.freshness&&snapshot.freshness.signalStatus||snapshot&&snapshot.health&&snapshot.health.status||"SUFFICIENT").toUpperCase();
    if(rows.length<CONFIG.minimumRows)return {tf,phase:"STALE / UNAVAILABLE",direction:null,available:false,stale:false,reasons:[`${tf} requires ${CONFIG.minimumRows} closed candles; received ${rows.length}`]};
    if(["STALE","FAILED","UNAVAILABLE"].includes(freshness))return {tf,phase:"STALE / UNAVAILABLE",direction:null,available:true,stale:true,reasons:[`${tf} evidence is ${freshness.toLowerCase()}`]};
    const ema9=emaSeries(rows,CONFIG.emaFastPeriod),ema55=emaSeries(rows,CONFIG.emaSlowPeriod),rangeAtr=atr(rows),gaps=ema9.map((value,index)=>value-ema55[index]);
    if(!(rangeAtr>0))return {tf,phase:"STALE / UNAVAILABLE",direction:null,available:false,stale:false,reasons:[`${tf} ATR is unavailable`]};
    const gap=gaps.at(-1),previousGap=gaps.at(-2),normalizedDistance=Math.abs(gap)/rangeAtr,previousDistance=Math.abs(previousGap)/rangeAtr,gapVelocity=previousDistance-normalizedDistance,relativeSlope=gap-previousGap,fastSlope=slope(ema9),slowSlope=slope(ema55),fastAcceleration=acceleration(ema9),slowAcceleration=acceleration(ema55),slowSlopeAtr=slowSlope/rangeAtr;
    const signs=gaps.map(value=>Math.sign(value)),crosses=[];for(let index=1;index<signs.length;index+=1)if(signs[index]&&signs[index-1]&&signs[index]!==signs[index-1])crosses.push(index);
    const latestCross=crosses.at(-1)??null,priorCross=crosses.at(-2)??null,barsSinceCross=latestCross==null?Infinity:rows.length-1-latestCross,recentSlice=gaps.slice(-CONFIG.bounceLookbackBars-1),recentDistances=recentSlice.map(value=>Math.abs(value)/rangeAtr),contactOffset=recentDistances.findLastIndex?recentDistances.findLastIndex(value=>value<=CONFIG.interactionBandAtr):(()=>{for(let i=recentDistances.length-1;i>=0;i-=1)if(recentDistances[i]<=CONFIG.interactionBandAtr)return i;return -1;})(),hadContact=contactOffset>=0,side=Math.sign(gap),sideDirection=directionForSide(side),approachDirection=relativeSlope>0?"LONG":relativeSlope<0?"SHORT":null;
    const flowByDirection={LONG:flowEvidence(rows,"LONG",rangeAtr),SHORT:flowEvidence(rows,"SHORT",rangeAtr)},flow=flowByDirection[sideDirection||approachDirection||"LONG"],responseProgress=flow.progressAtr,slowMeaningfullySloped=Math.abs(slowSlopeAtr)>=CONFIG.meaningfulSlowSlopeAtr;
    let phase="NO EVENT",direction=null,eventIndex=null,reasons=[];
    const rapidRecross=latestCross!=null&&priorCross!=null&&latestCross-priorCross<=CONFIG.crossFailureBars,lostFollowThrough=latestCross!=null&&barsSinceCross>0&&barsSinceCross<=CONFIG.crossFailureBars&&responseProgress<=CONFIG.failureProgressAtr;
    if(rapidRecross){phase="FAILED / INVALIDATED";direction=directionForSide(-Math.sign(gaps[latestCross]));eventIndex=latestCross;reasons.push(`Confirmed cross recrossed within ${latestCross-priorCross} closed candles`);}
    else if(lostFollowThrough){phase="FAILED / INVALIDATED";direction=sideDirection;eventIndex=latestCross;reasons.push("Confirmed cross lost directional follow-through inside the failure window");}
    else if(latestCross===rows.length-1){phase="CROSS CONFIRMED";direction=sideDirection;eventIndex=latestCross;reasons.push("EMA9 changed sides relative to EMA55 on the latest completed candle");}
    else if(latestCross!=null&&barsSinceCross<CONFIG.crossHoldBars){phase="CROSS CONFIRMED";direction=sideDirection;eventIndex=latestCross;reasons.push("Closed EMA9/EMA55 cross is awaiting a qualified hold or retest");}
    else if(latestCross!=null&&barsSinceCross>=CONFIG.crossHoldBars&&barsSinceCross<=CONFIG.bounceLookbackBars&&gaps.slice(latestCross).every(value=>Math.sign(value)===side)&&responseProgress>=CONFIG.responseProgressAtr){phase="RETEST / HOLD";direction=sideDirection;eventIndex=latestCross;reasons.push(`New 9/55 side held for ${barsSinceCross} completed candles`);}
    else if((latestCross==null||barsSinceCross>CONFIG.bounceLookbackBars)&&hadContact&&side&&gapVelocity<=-CONFIG.minimumExpansionAtr&&normalizedDistance>=CONFIG.bounceConfirmSeparationAtr&&responseProgress>=CONFIG.responseProgressAtr){phase="BOUNCE CONFIRMED";direction=sideDirection;eventIndex=rows.length-(recentDistances.length-contactOffset);reasons.push("Contact rejected without a closed crossover and directional separation followed");}
    else if((latestCross==null||barsSinceCross>CONFIG.bounceLookbackBars)&&hadContact&&side&&gapVelocity<0){phase="BOUNCE FORMING";direction=sideDirection;eventIndex=rows.length-(recentDistances.length-contactOffset);reasons.push("9/55 contact is separating on its original side");}
    else if(normalizedDistance<=CONFIG.interactionBandAtr){phase="CONTACT / COLLISION";direction=approachDirection||sideDirection;eventIndex=rows.length-1;reasons.push(`EMA9/EMA55 distance is inside the ${CONFIG.interactionBandAtr.toFixed(2)} ATR interaction band`);}
    else if(normalizedDistance<=CONFIG.approachBandAtr&&gapVelocity>=CONFIG.minimumContractionAtr){phase="APPROACH";direction=approachDirection;eventIndex=rows.length-1;reasons.push("EMA distance is contracting and relative slope points toward interaction");}
    const forecast=crossForecast(snapshot,tf,rows,ema9,ema55,rangeAtr,gapVelocity,fastSlope,slowSlope,fastAcceleration,slowAcceleration,flow);
    if(tf==="15m"&&forecast&&forecast.direction===approachDirection&&phase!=="CROSS CONFIRMED"&&phase!=="RETEST / HOLD"&&phase!=="FAILED / INVALIDATED"&&phase!=="BOUNCE CONFIRMED"){
      if(forecast.thresholdMet&&forecast.likelihoodScore>=CONFIG.forecastPossibleScore){phase="CROSS POSSIBLE ON CLOSE";direction=forecast.direction;reasons.push("Forming 15m price is beyond the calculated cross-on-close threshold");}
      else if(["APPROACH","CONTACT / COLLISION"].includes(phase)&&forecast.likelihoodScore>=CONFIG.forecastFormingScore){phase="CROSS FORMING";direction=forecast.direction;reasons.push("Cross-on-close inputs are developing but remain unconfirmed");}
    }
    const distanceFromInteractionAtr=Math.abs((num(rows.at(-1).close)??ema55.at(-1))-ema55.at(-1))/rangeAtr;
    if(!direction&&latestCross!=null&&barsSinceCross<=CONFIG.extendedEventPersistenceBars){direction=sideDirection;eventIndex=latestCross;reasons.push("Recent confirmed cross remains the active interaction origin");}
    if(direction&&!["APPROACH","CONTACT / COLLISION","CROSS POSSIBLE ON CLOSE","CROSS FORMING","FAILED / INVALIDATED"].includes(phase)&&distanceFromInteractionAtr>CONFIG.chaseDistanceAtr){phase="EXTENDED / NO CHASE";reasons.push(`Price is ${distanceFromInteractionAtr.toFixed(2)} ATR from the EMA55 interaction area`);}
    const eventTime=eventIndex==null?null:num(rows[eventIndex]&&rows[eventIndex].time),eventAgeBars=eventIndex==null?Infinity:rows.length-1-eventIndex,geometryScore=clamp(100-normalizedDistance*70+(gapVelocity>0?8:0)+(slowMeaningfullySloped?8:-8));
    return {tf,phase,direction,available:true,stale:false,eventTime,eventGeneration:eventTime||num(rows.at(-1).time)||0,eventAgeBars,ema9:ema9.at(-1),ema55:ema55.at(-1),gap,normalizedDistance,gapVelocity,fastSlope,slowSlope,fastAcceleration,slowAcceleration,relativeSlope,slowSlopeAtr,slowMeaningfullySloped,responseProgress,distanceFromInteractionAtr,geometryScore,flow,flowByDirection,forecast,reasons:unique(reasons),fixtureDiagnostics:{crosses,barsSinceCross,hadContact,rangeAtr,previousGap,eventAgeBars}};
  }
  function secondaryBackdrop(snapshot,direction){
    const rows=closedRows(snapshot,"15m");if(rows.length<CONFIG.minimumRows)return {available:false,score:null,supporting:[],opposing:["15m secondary backdrop unavailable"]};
    const close=num(rows.at(-1).close),side=sideValue(direction),rangeAtr=atr(rows)||1,e21=emaSeries(rows,CONFIG.emaSecondaryPeriod).at(-1),e100=emaSeries(rows,100).at(-1),e200=emaSeries(rows,200).at(-1),recent=rows.slice(-30),volumeTotal=recent.reduce((sum,row)=>sum+(num(row.volume)||0),0),vwap=volumeTotal?recent.reduce((sum,row)=>sum+((num(row.high)+num(row.low)+num(row.close))/3)*(num(row.volume)||0),0)/volumeTotal:null;
    const levels=[{name:"EMA21",value:e21,weight:10},{name:"EMA100",value:e100,weight:12},{name:"EMA200",value:e200,weight:14},{name:"VWAP",value:vwap,weight:8}],supporting=[],opposing=[];let score=50;
    levels.forEach(level=>{if(level.value==null)return;const aligned=(close-level.value)*side>=0;if(aligned){score+=level.weight;supporting.push(`${level.name} is aligned`);}else{score-=level.weight;opposing.push(`${level.name} opposes within ${(Math.abs(close-level.value)/rangeAtr).toFixed(2)} ATR`);}});
    const structure=snapshot&&snapshot.structureByTf&&snapshot.structureByTf["15m"];if(structure)supporting.push("15m structure snapshot available as secondary context");
    return {available:true,score:clamp(score),ema21:e21,ema100:e100,ema200:e200,vwap,supporting,opposing};
  }
  function synchronization(phases,direction,horizonId){
    const weights=CONFIG.horizonWeights[horizonId]||CONFIG.horizonWeights.quick,side=sideValue(direction),supporting=[],opposing=[],unavailable=[];let score=45;
    const assess=(tf,weight)=>{const phase=phases[tf],freshnessBars=CONFIG.synchronizationFreshness[tf]??0,eventAgeBars=Number.isFinite(Number(phase&&phase.eventAgeBars))?Number(phase.eventAgeBars):0;if(!phase||!phase.available||phase.stale){unavailable.push(tf);return;}if(eventAgeBars>freshnessBars){opposing.push(`${tf} ${phase.phase} is stale at ${eventAgeBars} bars`);return;}if(phase.direction===direction&&phase.phase!=="NO EVENT"){score+=weight;supporting.push(`${tf} ${phase.phase} aligns`);}else if(phase.direction&&phase.direction!==direction&&!["NO EVENT","APPROACH"].includes(phase.phase)){score-=weight*.8;opposing.push(`${tf} ${phase.phase} favors ${phase.direction}`);}};
    assess("5m",weights.lead);assess("30m",weights.intermediate);assess("1h",weights.broad);
    const consecutive=["5m","15m","30m","1h"].filter(tf=>phases[tf]&&phases[tf].direction===direction&&!["NO EVENT","STALE / UNAVAILABLE","FAILED / INVALIDATED"].includes(phases[tf].phase)).length;if(consecutive>=CONFIG.consecutiveSynchronizationMinimum){score+=8;supporting.push(`${consecutive} timeframes have compatible directional phases`);}
    const strongMatureOpposition=["30m","1h"].some(tf=>phases[tf]&&phases[tf].direction&&phases[tf].direction!==direction&&["BOUNCE CONFIRMED","CROSS CONFIRMED","RETEST / HOLD"].includes(phases[tf].phase));
    return {score:clamp(score),supporting,opposing,unavailable,strongMatureOpposition,alignedCount:consecutive,side};
  }
  function phaseScore(phase){return ({"NO EVENT":0,APPROACH:55,"CONTACT / COLLISION":68,"BOUNCE FORMING":72,"BOUNCE CONFIRMED":96,"CROSS POSSIBLE ON CLOSE":62,"CROSS FORMING":58,"CROSS CONFIRMED":72,"RETEST / HOLD":94,"FAILED / INVALIDATED":18,"EXTENDED / NO CHASE":45,"STALE / UNAVAILABLE":null})[phase];}
  function phaseToState(phase,{actionable=false,earlyWarning=false}={}){
    if(phase==="FAILED / INVALIDATED")return "SETUP FAILED";if(phase==="EXTENDED / NO CHASE")return "NO CHASE";if(phase==="NO EVENT"||phase==="STALE / UNAVAILABLE")return earlyWarning?"WATCHING":"NO SETUP";if(phase==="APPROACH")return "WATCHING";if(phase==="CONTACT / COLLISION")return "STAND BY";if(actionable)return "TRIGGER ACTIVE";return "TRIGGER FORMING";
  }
  function evaluateModel(facts,{horizonId="quick",directionMode="AUTO",symbol="",version=0,publicationGeneration=0}={}){
    const mode=["LONG","SHORT"].includes(String(directionMode).toUpperCase())?String(directionMode).toUpperCase():"AUTO",phases=facts.timeframes||{},primary=phases["15m"]||{phase:"STALE / UNAVAILABLE",direction:null,available:false,stale:false,reasons:["15m evidence unavailable"]},lead=phases["5m"]||null;
    const automaticDirection=primary.direction||lead&&lead.direction||null,evaluatedDirection=mode==="AUTO"?automaticDirection:mode,direction=evaluatedDirection||"NO BIAS",selectedPrimary=primary.direction===evaluatedDirection?primary:{...primary,phase:primary.phase==="STALE / UNAVAILABLE"?primary.phase:"NO EVENT",direction:evaluatedDirection,reasons:unique([...(primary.reasons||[]),primary.direction&&primary.direction!==evaluatedDirection?`15m evidence favors ${primary.direction}, not selected ${evaluatedDirection}`:null])};
    const sync=evaluatedDirection?synchronization(phases,evaluatedDirection,horizonId):{score:0,supporting:[],opposing:[],unavailable:CORE_TIMEFRAMES,strongMatureOpposition:false,alignedCount:0},secondary=evaluatedDirection?(facts.secondary||secondaryBackdrop(facts.snapshot,evaluatedDirection)):{available:false,score:null,supporting:[],opposing:[]},flow=selectedPrimary.flowByDirection&&selectedPrimary.flowByDirection[evaluatedDirection]||primary.direction===evaluatedDirection&&selectedPrimary.flow||{score:0,effective:false,absorption:false,highVolumeNoProgress:false,uncontrolled:false,progressAtr:0,evidence:[]},selectedResponseProgress=num(flow.progressAtr)??(primary.direction===evaluatedDirection?selectedPrimary.responseProgress:0)??0,rawInteractionScore=phaseScore(selectedPrimary.phase),interactionScore=Number.isFinite(rawInteractionScore)?clamp(rawInteractionScore-(selectedPrimary.slowMeaningfullySloped===false?8:0)):null,responseScore=clamp(45+selectedResponseProgress*70+(flow.absorption?18:0)),volumeScore=flow.score,secondaryScore=secondary.score;
    const missingCore=CORE_TIMEFRAMES.filter(tf=>!phases[tf]||!phases[tf].available),staleCore=CORE_TIMEFRAMES.filter(tf=>phases[tf]&&phases[tf].stale),dataStatus=missingCore.includes("15m")?"unavailable":staleCore.length?"stale":"sufficient",noChase=selectedPrimary.phase==="EXTENDED / NO CHASE"||selectedPrimary.distanceFromInteractionAtr>CONFIG.chaseDistanceAtr,confirmedPhase=["BOUNCE CONFIRMED","RETEST / HOLD"].includes(selectedPrimary.phase),qualifiedResponse=responseScore>=CONFIG.minimumQualifiedResponseScore&&(flow.effective||flow.absorption),actionable=confirmedPhase&&qualifiedResponse&&!noChase&&!sync.strongMatureOpposition&&dataStatus==="sufficient",earlyWarning=selectedPrimary.phase==="NO EVENT"&&lead&&lead.direction===evaluatedDirection&&["APPROACH","CONTACT / COLLISION","CROSS FORMING","CROSS POSSIBLE ON CLOSE"].includes(lead.phase),visibleState=phaseToState(selectedPrimary.phase,{actionable,earlyWarning}),presentation=PRESENTATION[visibleState]||PRESENTATION["NO SETUP"];
    const componentValues=[interactionScore,sync.score,responseScore,volumeScore,secondaryScore].filter(Number.isFinite),confidence=direction==="NO BIAS"||!componentValues.length?null:Math.round(clamp((interactionScore||0)*.34+sync.score*.20+responseScore*.20+(volumeScore||0)*.16+(secondaryScore||0)*.10-(sync.strongMatureOpposition?10:0)-(dataStatus==="stale"?15:0)));
    const setupIdentity=selectedPrimary.phase==="NO EVENT"||selectedPrimary.phase==="STALE / UNAVAILABLE"?null:[symbol,"15m",evaluatedDirection,selectedPrimary.eventGeneration||version,"EMA9/EMA55"].join("|"),alertIdentity=evaluatedDirection&&ALERT_PHASES.has(selectedPrimary.phase)?[symbol,evaluatedDirection,"15m",selectedPrimary.eventGeneration||version,selectedPrimary.phase].join("|"):null,invalidation=selectedPrimary.ema55==null?null:selectedPrimary.ema55-sideValue(evaluatedDirection)*(selectedPrimary.fixtureDiagnostics&&selectedPrimary.fixtureDiagnostics.rangeAtr||0)*.35;
    const supporting=unique([...(selectedPrimary.reasons||[]),...(sync.supporting||[]),...(flow.evidence||[]),...(secondary.supporting||[])]),opposing=unique([...(sync.opposing||[]),...(secondary.opposing||[]),primary.direction&&primary.direction!==evaluatedDirection?`Automatic 15m evidence favors ${primary.direction}`:null,flow.highVolumeNoProgress&&!flow.absorption?"High volume has insufficient directional progress":null,flow.uncontrolled?"Extreme range expansion lacks a controlled hold":null,...missingCore.map(tf=>`${tf} unavailable`),...staleCore.map(tf=>`${tf} stale`)]),reason=visibleState==="TRIGGER ACTIVE"?`${selectedPrimary.phase} has qualified 15m response and synchronization`:visibleState==="NO CHASE"?`15m event is extended ${Number(selectedPrimary.distanceFromInteractionAtr||0).toFixed(2)} ATR from interaction`:visibleState==="SETUP FAILED"?"The selected 15m 9/55 event failed or rapidly recrossed":earlyWarning?`5m ${lead.phase} is an early warning; 15m remains NO EVENT`:(selectedPrimary.reasons&&selectedPrimary.reasons[0])||"No authoritative 15m 9/55 event";
    const setupGrade=grade(interactionScore),triggerGrade=grade(average([responseScore,volumeScore])),currentGrade=noChase?"UNACCEPTABLE":grade(average([confidence,secondaryScore])),decision={state:visibleState==="TRIGGER ACTIVE"?"READY":visibleState==="WATCHING"?"SETUP ARMED":visibleState==="STAND BY"?"ZONE ENGAGED":visibleState==="TRIGGER FORMING"?"TRIGGER DEVELOPING":visibleState==="SETUP FAILED"?"INVALIDATED":visibleState==="NO CHASE"?"EXPIRED":"BIAS CONFIRMED",direction:evaluatedDirection,family:setupIdentity?"EMA9/EMA55 phase synchronization":null,tf:setupIdentity?"15m":null,setupIdentity,horizonId,triggerIdentity:alertIdentity,triggerState:actionable?"active":visibleState==="TRIGGER FORMING"?"developing":"absent",reason,interaction:{interactionTime:selectedPrimary.eventTime||null,reactionTime:confirmedPhase?selectedPrimary.eventTime||null:null,evidence:selectedPrimary.reasons||[]},pressure:{triggerTf:"15m",primaryTf:"15m",evidence:flow.evidence||[],effectiveOpposition:sync.strongMatureOpposition},assessments:{setup:{score:interactionScore,grade:setupGrade},trigger:{score:average([responseScore,volumeScore]),grade:triggerGrade},current:{score:confidence,grade:currentGrade}}};
    const candidateForecast=selectedPrimary.forecast||primary.forecast||null,forecast=candidateForecast&&candidateForecast.direction===evaluatedDirection?candidateForecast:null,detailLines=[`Evaluated direction: ${direction}`,`Authoritative 15m phase: ${selectedPrimary.phase}`,`Synchronization: 5m ${phases["5m"]&&phases["5m"].phase||"UNAVAILABLE"} | 15m ${selectedPrimary.phase} | 30m ${phases["30m"]&&phases["30m"].phase||"UNAVAILABLE"} | 1h ${phases["1h"]&&phases["1h"].phase||"UNAVAILABLE"}`,`15m EMA9/EMA55 gap: ${selectedPrimary.gap==null?"UNAVAILABLE":selectedPrimary.gap.toFixed(6)} (${selectedPrimary.normalizedDistance==null?"UNAVAILABLE":selectedPrimary.normalizedDistance.toFixed(3)+" ATR"})`,`15m slopes: EMA9 ${selectedPrimary.fastSlope==null?"UNAVAILABLE":selectedPrimary.fastSlope.toFixed(6)} | EMA55 ${selectedPrimary.slowSlope==null?"UNAVAILABLE":selectedPrimary.slowSlope.toFixed(6)}`,`Interaction freshness: ${dataStatus.toUpperCase()}`,forecast?`Required 15m cross close: ${forecast.direction} ${forecast.direction==="LONG"?">=":"<="} ${forecast.requiredClose.toFixed(6)}; current ${forecast.currentPrice.toFixed(6)}; ${forecast.distanceBps.toFixed(1)} bps / ${forecast.distanceAtr.toFixed(2)} ATR; ${forecast.timeRemainingMs==null?"time unavailable":Math.ceil(forecast.timeRemainingMs/1000)+"s remaining"}`:"Cross-on-close threshold: not applicable",forecast?`${forecast.label}: ${forecast.likelihoodScore}/100`:"Cross-likelihood score: unavailable",`Participation/flow: ${(flow.evidence||[]).join("; ")||"UNAVAILABLE"}`,`Secondary backdrop: ${[...(secondary.supporting||[]),...(secondary.opposing||[])].join("; ")||"UNAVAILABLE"}`,`Invalidation: ${invalidation==null?"UNAVAILABLE":invalidation.toFixed(6)}`,noChase?`NO CHASE: ${reason}`:"NO CHASE: not active"];
    const comparisonDiagnostics={directionMode:mode,evaluatedDirection,automaticDirection,authoritativePhase:selectedPrimary.phase,directionalPermissionScore:interactionScore,directionalPermissionBreakdown:{interactionGeometry:interactionScore,multiTimeframeSynchronization:sync.score,postInteractionResponse:responseScore,volumeParticipationEffectiveness:volumeScore,secondaryBackdrop:secondaryScore},setupScore:interactionScore,setupBreakdown:{interactionGeometry:interactionScore,slowEmaSlopeMeaningful:selectedPrimary.slowMeaningfullySloped===true?100:selectedPrimary.slowMeaningfullySloped===false?45:null},triggerScore:average([responseScore,volumeScore]),triggerBreakdown:{postInteractionResponse:responseScore,volumeParticipationEffectiveness:volumeScore},currentEntryScore:confidence,currentEntryBreakdown:{secondaryBackdrop:secondaryScore,chaseRisk:noChase?0:100},hardGates:{passed:unique([dataStatus==="sufficient"&&"fresh15m",selectedPrimary.phase!=="NO EVENT"&&"authoritativeEvent",qualifiedResponse&&"qualifiedResponse",!noChase&&"notChased"]),failed:unique([dataStatus!=="sufficient"&&"fresh15m",selectedPrimary.phase==="NO EVENT"&&"authoritativeEvent",!qualifiedResponse&&"qualifiedResponse",noChase&&"notChased"])},effectiveOppositionEvidence:opposing,volatilityRegime:flow.uncontrolled?"Disorderly/extreme":"Event-window controlled",participationState:flow.participationRatio==null?"UNAVAILABLE":flow.participationRatio>=CONFIG.strongParticipationRatio?"STRONG":flow.participationRatio<CONFIG.weakParticipationRatio?"WEAK":"NORMAL",participation:flow,flowEffectiveness:flow,chaseDistanceAtr:selectedPrimary.distanceFromInteractionAtr??null,remainingRewardRisk:null,finalStateReason:reason,engineVersion:VERSION,publicationGeneration,signalC:{signalId:SIGNAL_ID,authoritativeTimeframe:"15m",authoritativePhase:selectedPrimary.phase,timeframes:phases,synchronization:sync,crossForecast:forecast,components:{interactionGeometry:interactionScore,multiTimeframeSynchronization:sync.score,postInteractionResponse:responseScore,volumeParticipationEffectiveness:volumeScore,secondaryBackdrop:secondaryScore},supporting,opposing,secondary,invalidation,noChase,detailLines}};
    return {direction,confidence,entryState:visibleState,setupIdentity,setupFamily:setupIdentity?"EMA9/EMA55 phase synchronization":null,setupTimeframe:setupIdentity?"15m":null,setupQuality:setupGrade,triggerQuality:triggerGrade,currentEntryQuality:currentGrade,entryVerdict:actionable?`READY ${evaluatedDirection}`:"WAIT",reasons:unique([reason,...supporting,...opposing]),exclusions:opposing,triggerIdentity:alertIdentity,triggerEvidence:selectedPrimary.reasons||[],dataStatus,tone:presentation.tone,visibleState,definition:presentation.definition,decision,comparisonDiagnostics,detailLines,evaluatedDirection,authoritativePhase:selectedPrimary.phase,crossForecast:forecast};
  }
  function extractFacts(snapshot){const timeframes=Object.fromEntries(CORE_TIMEFRAMES.map(tf=>[tf,analyzeTimeframe(snapshot,tf)]));return {snapshot,timeframes};}
  function createState(){return {evidenceByTf:new Map(),smcCache:new Map(),entryTrackers:new Map(),setupHistories:new Map(),seenTriggerAlertIds:new Set(),seenTriggerAlertOrder:[],evaluationCache:new Map(),fingerprints:new Map()};}
  function clearState(state){Object.values(state).forEach(value=>{if(value instanceof Map||value instanceof Set)value.clear();else if(Array.isArray(value))value.length=0;});}
  function createSignalEngineC(){
    const state=createState();let calculations=0,cacheHits=0,activations=0,deactivations=0,lastDiagnostics=null;
    return {
      id:"C",signalId:SIGNAL_ID,displayName:"Signal C — 9/55",version:VERSION,status:"available",state,
      getRequirements(context={}){const horizonId=["quick","2_3h","6_8h"].includes(context.horizonId)?context.horizonId:"quick",slots=[9,21,55,100,200].map((period,index)=>({slotId:`MA${index+1}`,period})),items=CORE_TIMEFRAMES.map(tf=>({tf,historyTarget:DEPTHS[tf],roles:tf==="5m"?["5m phase-leading warning"]:tf==="15m"?["15m authoritative EMA9/EMA55 event and confirmation"]:tf==="30m"?["30m intermediate phase synchronization"]:["1h broad phase synchronization and regime"],signalRequired:true,managementRequired:false}));return {horizonId,engine:{id:"C",signalId:SIGNAL_ID,authoritativeTimeframe:"15m"},slots,items,timeframes:[...CORE_TIMEFRAMES]};},
      evaluate(context={}){if(!context.snapshot)throw new Error("Signal C market snapshot is unavailable");const horizonId=["quick","2_3h","6_8h"].includes(context.horizonId)?context.horizonId:"quick",directionMode=["LONG","SHORT"].includes(String(context.directionMode||"AUTO").toUpperCase())?String(context.directionMode).toUpperCase():"AUTO",facts=extractFacts(context.snapshot),automaticDirection=facts.timeframes["15m"].direction||facts.timeframes["5m"].direction||null,evaluatedDirection=directionMode==="AUTO"?(automaticDirection||"NO BIAS"):directionMode,fingerprint=[context.snapshot.signature||context.snapshot.version,horizonId,directionMode,evaluatedDirection].join("|"),publicationGeneration=Number(context.publicationGeneration)||0;if(state.evaluationCache.has(fingerprint)){cacheHits+=1;const cached=state.evaluationCache.get(fingerprint);cached.comparisonDiagnostics.publicationGeneration=publicationGeneration;lastDiagnostics=cached.comparisonDiagnostics;return cached;}calculations+=1;const result=evaluateModel(facts,{horizonId,directionMode,symbol:context.snapshot.symbol,version:context.snapshot.version,publicationGeneration});state.evaluationCache.set(fingerprint,result);state.fingerprints.set(`${horizonId}|${directionMode}|${evaluatedDirection}`,fingerprint);lastDiagnostics=result.comparisonDiagnostics;while(state.evaluationCache.size>24)state.evaluationCache.delete(state.evaluationCache.keys().next().value);return result;},
      evaluateFacts(facts,metadata={}){return evaluateModel(facts,metadata);},extractFacts,
      onActivate(){activations+=1;},onDeactivate(){deactivations+=1;clearState(state);},reset(){clearState(state);},
      diagnostics(){return {calculations,cacheHits,activations,deactivations,cacheCounts:{evidenceByTf:state.evidenceByTf.size,setupHistories:state.setupHistories.size,evaluationCache:state.evaluationCache.size,fingerprints:state.fingerprints.size},lastPublication:lastDiagnostics,configuration:CONFIG,phases:PHASES,signalId:SIGNAL_ID,authoritativeTimeframe:"15m"};},
      _test:Object.freeze({CONFIG,PHASES,crossClosePrice,emaSeries,flowEvidence,analyzeTimeframe,evaluateModel,secondaryBackdrop,synchronization,alertIdentity:({symbol,direction,eventGeneration,phase})=>ALERT_PHASES.has(phase)?[symbol,direction,"15m",eventGeneration,phase].join("|"):null})
    };
  }
  Object.defineProperty(window,"createSignalEngineC",{value:createSignalEngineC,configurable:true});
})();
