(() => {
  "use strict";

  const VERSION="1.1.0";
  const DEPTHS=Object.freeze({"1m":2900,"3m":980,"5m":596,"15m":320,"1h":320,"4h":320,"1d":320});
  const PROFILES=Object.freeze({
    quick:Object.freeze({early:"1m",trigger:"3m",primary:"5m",setups:["3m","5m"],structures:["15m","1h"],boundaries:["4h","1d"],eventWindow:7,chaseAtr:1.35,minNetRr:1.35}),
    "2_3h":Object.freeze({early:"3m",trigger:"5m",primary:"15m",setups:["5m","15m"],structures:["1h"],boundaries:["4h","1d"],eventWindow:7,chaseAtr:1.55,minNetRr:1.45}),
    "6_8h":Object.freeze({early:"5m",trigger:"15m",primary:"1h",setups:["15m","1h"],structures:["4h"],boundaries:["1d"],eventWindow:8,chaseAtr:1.75,minNetRr:1.55})
  });
  const GRADE=value=>value>=80?"A":value>=70?"B":value>=60?"C":"UNACCEPTABLE";
  const PRESENTATION=Object.freeze({
    "WATCHING":Object.freeze({definition:"A VALID SETUP AREA EXISTS, BUT PRICE HAS NOT REACHED IT YET.",tone:"gray",internal:"SETUP ARMED"}),
    "STAND BY":Object.freeze({definition:"PRICE IS AT THE SETUP AREA; WAIT FOR A CLOSED REACTION.",tone:"orange",internal:"ZONE ENGAGED"}),
    "TRIGGER FORMING":Object.freeze({definition:"THE SETUP REACTION EXISTS, BUT POST-INTERACTION CONFIRMATION IS INCOMPLETE.",tone:"orange",internal:"TRIGGER DEVELOPING"}),
    "TRIGGER ACTIVE":Object.freeze({definition:"PRICE IS DEMONSTRABLY JOINING THE INTENDED MOVE AFTER THE SETUP INTERACTION.",tone:"green",internal:"READY"}),
    "NO CHASE":Object.freeze({definition:"THE SETUP MOVED TOO FAR FROM ITS VALID ORIGIN FOR AN EFFICIENT NEW ENTRY.",tone:"red",internal:"EXPIRED"}),
    "SETUP FAILED":Object.freeze({definition:"A CLOSED CANDLE INVALIDATED THE SETUP OR REQUIRED REACTION.",tone:"red",internal:"INVALIDATED"}),
    "NO SETUP":Object.freeze({definition:"DIRECTIONAL PERMISSION EXISTS, BUT NO VALID ENTRY SETUP IS AVAILABLE.",tone:"gray",internal:"BIAS CONFIRMED"})
  });

  const num=value=>{const parsed=Number(value);return Number.isFinite(parsed)?parsed:null;};
  const clamp=(value,min=0,max=100)=>Math.max(min,Math.min(max,Number(value)||0));
  const average=values=>{const usable=values.map(Number).filter(Number.isFinite);return usable.length?usable.reduce((sum,value)=>sum+value,0)/usable.length:0;};
  const sideValue=direction=>direction==="LONG"?1:direction==="SHORT"?-1:0;
  const unique=values=>[...new Set((values||[]).filter(Boolean))];
  function closedRows(snapshot,tf){return (snapshot&&snapshot.closedByTf&&snapshot.closedByTf[tf]||[]).filter(row=>row&&row.final!==false&&num(row.close)!=null);}
  function trueRange(row,previous){const priorClose=num((previous&&previous.close)??row.open);return Math.max(num(row.high)-num(row.low),Math.abs(num(row.high)-priorClose),Math.abs(num(row.low)-priorClose));}
  function atr(rows,period=14){const source=rows.slice(-(period+1));if(source.length<3)return null;return average(source.slice(1).map((row,index)=>trueRange(row,source[index])));}
  function emaSeries(rows,period){
    if(rows.length<period)return [];
    const alpha=2/(period+1),series=[];let value=average(rows.slice(0,period).map(row=>row.close));
    series.push(value);for(let index=period;index<rows.length;index+=1){value=num(rows[index].close)*alpha+value*(1-alpha);series.push(value);}return series;
  }
  function emaSnapshot(rows){
    const out={};[9,21,55,100,200].forEach(period=>{const series=emaSeries(rows,period);out[period]={value:series.at(-1)??null,prior:series.at(-4)??series[0]??null,series};});return out;
  }
  function percentile(values,current){const usable=values.map(Number).filter(Number.isFinite).sort((a,b)=>a-b);if(!usable.length||!Number.isFinite(current))return null;return 100*usable.filter(value=>value<=current).length/usable.length;}
  function volatilityEvidence(rows){
    const currentAtr=atr(rows),ranges=rows.slice(-100).map((row,index,list)=>index?trueRange(row,list[index-1]):num(row.high)-num(row.low));
    const rank=percentile(ranges.slice(0,-1),average(ranges.slice(-5))),ratio=currentAtr&&average(ranges.slice(-5))/currentAtr||null;
    const regime=rank==null?"Unavailable":rank<25?"Compressed":rank<70?"Normal":rank<92?"Expanding/controlled":"Disorderly/extreme";
    return {atr:currentAtr,realizedRangePercentile:rank,rangeToAtr:ratio,regime,controlledAcceptance:regime!=="Disorderly/extreme"};
  }
  function candleFlow(rows,direction,window=8){
    const side=sideValue(direction),sample=rows.slice(-window),first=sample[0],last=sample.at(-1),rangeAtr=atr(rows)||average(sample.map(row=>num(row.high)-num(row.low)))||1;
    const totalVolume=sample.reduce((sum,row)=>sum+(num(row.volume)||0),0),buy=sample.reduce((sum,row)=>sum+(num(row.takerBuyBase)||0),0);
    const imbalance=totalVolume>0?(buy-(totalVolume-buy))/totalVolume:0;
    const progress=first&&last?(num(last.close)-num(first.open))*side/rangeAtr:0;
    const directionalImbalance=imbalance*side,efficiency=totalVolume>0?progress/Math.max(.25,Math.abs(directionalImbalance)*4):progress;
    const directionalCloses=sample.filter(row=>(num(row.close)-num(row.open))*side>0).length/Math.max(1,sample.length);
    const wickPenalty=average(sample.map(row=>{const range=Math.max(1e-9,num(row.high)-num(row.low)),body=Math.abs(num(row.close)-num(row.open));return 1-body/range;}));
    const effective=progress>=.28&&directionalCloses>=.5&&(directionalImbalance>=-.08||progress>=.65);
    const absorption=directionalImbalance<-.08&&progress>=.42&&directionalCloses>=.57;
    const ineffectiveHighVolume=Math.abs(directionalImbalance)>=.16&&progress<.16;
    return {effective:effective||absorption,absorption,ineffectiveHighVolume,directionalImbalance,priceProgressAtr:progress,efficiency,directionalCloseShare:directionalCloses,wickPenalty,evidence:[`Directional taker imbalance ${(directionalImbalance*100).toFixed(1)}%`,`Resulting price progress ${progress.toFixed(2)} ATR`,`Directional closes ${(directionalCloses*100).toFixed(0)}%`]};
  }
  function participationEvidence(rows,eventRows,direction){
    const baselineRows=rows.slice(-60,-Math.max(1,eventRows.length)),baselineVolume=average(baselineRows.map(row=>num(row.volume)||0)),baselineQuote=average(baselineRows.map(row=>num(row.quoteVolume)||0)),baselineTrades=average(baselineRows.map(row=>num(row.tradeCount)||0));
    const eventVolume=average(eventRows.map(row=>num(row.volume)||0)),eventQuote=average(eventRows.map(row=>num(row.quoteVolume)||0)),eventTrades=average(eventRows.map(row=>num(row.tradeCount)||0));
    const volumeRatio=baselineVolume?eventVolume/baselineVolume:null,quoteRatio=baselineQuote?eventQuote/baselineQuote:null,tradeRatio=baselineTrades?eventTrades/baselineTrades:null;
    const available=[volumeRatio,quoteRatio,tradeRatio].filter(Number.isFinite),ratio=available.length?average(available):null;
    const persistence=eventRows.length?eventRows.filter(row=>(num(row.close)-num(row.open))*sideValue(direction)>0).length/eventRows.length:0;
    const score=ratio==null?50:clamp(35+ratio*30+persistence*25,0,100),state=ratio==null?"UNAVAILABLE":ratio>=1.15?"STRONG":ratio>=.8?"NORMAL":"WEAK";
    return {state,score,volumeRatio,quoteVolumeRatio:quoteRatio,tradeCountRatio:tradeRatio,persistence,credibleAbsorption:false};
  }
  function swingPoints(rows){
    const highs=[],lows=[];for(let index=2;index<rows.length-2;index+=1){const row=rows[index];if(num(row.high)>=Math.max(...rows.slice(index-2,index+3).map(item=>num(item.high))))highs.push({index,time:row.time,price:num(row.high)});if(num(row.low)<=Math.min(...rows.slice(index-2,index+3).map(item=>num(item.low))))lows.push({index,time:row.time,price:num(row.low)});}return {highs,lows};
  }
  function setupCandidates(snapshot,profile,direction,volatility){
    const side=sideValue(direction),candidates=[];
    for(const tf of profile.setups){
      const rows=closedRows(snapshot,tf),current=rows.at(-1),currentPrice=num(snapshot.currentPrice)??num(current&&current.close),rangeAtr=atr(rows)||volatility.atr;
      if(rows.length<30||currentPrice==null||!(rangeAtr>0))continue;
      const emas=emaSnapshot(rows),width=rangeAtr*(volatility.regime==="Disorderly/extreme"?.28:volatility.regime==="Compressed"?.12:.18);
      const add=(family,level,activationIndex,quality,extra={})=>{if(!Number.isFinite(level))return;const zone={low:level-width,high:level+width},after=Math.max(0,activationIndex||rows.length-10),interactions=[];rows.slice(after).forEach((row,index)=>{if(num(row.low)<=zone.high&&num(row.high)>=zone.low)interactions.push(after+index);});const interactionIndex=interactions.at(-1)??null;const reactionRow=interactionIndex==null?null:rows[interactionIndex],body=reactionRow?(num(reactionRow.close)-num(reactionRow.open))*side:0,reactionConfirmed=!!reactionRow&&body>=rangeAtr*.12&&(num(reactionRow.close)-level)*side>=-width*.15;const invalidation=level-side*rangeAtr*.65,invalidated=interactionIndex!=null&&rows.slice(interactionIndex).some(row=>(num(row.close)-invalidation)*side<0);const distanceAtr=Math.max(0,currentPrice<zone.low?zone.low-currentPrice:currentPrice>zone.high?currentPrice-zone.high:0)/rangeAtr;candidates.push({family,tf,direction,level,zone,invalidation,activationIndex:after,interactionIndex,interactionTime:interactionIndex==null?null:rows[interactionIndex].time,interacted:interactionIndex!=null,reactionConfirmed,invalidated,distanceAtr,repeatedTests:interactions.length,quality,nonEma:!/^MA/.test(family),rows,...extra});};
      const pivots=swingPoints(rows.slice(-80)),baseIndex=Math.max(0,rows.length-80);
      const relevant=direction==="LONG"?pivots.highs:pivots.lows;
      [...relevant].reverse().slice(0,5).forEach(pivot=>{const index=baseIndex+pivot.index,broken=rows.slice(index+1).findIndex(row=>(num(row.close)-pivot.price)*side>rangeAtr*.08);if(broken>=0)add("Structural retest",pivot.price,index+1+broken,82,{structural:true});});
      const recent=rows.slice(-12);for(let index=2;index<recent.length;index+=1){const prior=recent.slice(Math.max(0,index-5),index),boundary=direction==="LONG"?Math.min(...prior.map(row=>num(row.low))):Math.max(...prior.map(row=>num(row.high))),row=recent[index],swept=direction==="LONG"?num(row.low)<boundary:num(row.high)>boundary,reclaimed=(num(row.close)-boundary)*side>0;if(swept&&reclaimed)add(direction==="LONG"?"Sweep and reclaim":"Sweep and rejection",boundary,rows.length-recent.length+index,86,{structural:true,sweep:true});}
      for(const period of [9,21]){const level=emas[period].value,near=recent.findIndex(row=>num(row.low)<=level+width&&num(row.high)>=level-width&&(num(row.close)-level)*side>0);if(near>=0)add(`MA${period} bounce/rejection`,level,rows.length-recent.length+near,period===21?78:72,{maPeriod:period});}
      const min=Math.min(emas[9].series.length,emas[21].series.length),fast=emas[9].series.slice(-min),slow=emas[21].series.slice(-min),offset=rows.length-min;for(let index=Math.max(1,min-12);index<min;index+=1){const before=(fast[index-1]-slow[index-1])*side,after=(fast[index]-slow[index])*side;if(before<=0&&after>0)add("MA crossover retest",slow[index],offset+index,74,{maPeriod:21,crossover:true});}
      const historicalRanges=rows.slice(-50,-10).map(row=>num(row.high)-num(row.low)),compressed=average(rows.slice(-10,-2).map(row=>num(row.high)-num(row.low)))<average(historicalRanges)*.68;const compressionBoundary=direction==="LONG"?Math.max(...rows.slice(-10,-2).map(row=>num(row.high))):Math.min(...rows.slice(-10,-2).map(row=>num(row.low))),release=rows.slice(-2).findIndex(row=>(num(row.close)-compressionBoundary)*side>rangeAtr*.18);if(compressed)add("Compression release",compressionBoundary,release>=0?rows.length-2+release:rows.length-2,release>=0?76:62,{compression:true,released:release>=0});
    }
    return candidates.sort((a,b)=>{const aScore=a.quality-(a.distanceAtr*8)+(a.structural?4:0),bScore=b.quality-(b.distanceAtr*8)+(b.structural?4:0);return bScore-aScore;});
  }
  function directionEvidence(snapshot,profile,directionMode="AUTO"){
    const primary=closedRows(snapshot,profile.primary),structuralSets=profile.structures.map(tf=>closedRows(snapshot,tf)),boundarySets=profile.boundaries.map(tf=>closedRows(snapshot,tf));
    const primaryAtr=atr(primary)||1,primaryEma=emaSnapshot(primary),alignment=(sets,direction,period=55)=>{const side=sideValue(direction),scores=sets.map(rows=>{const latest=rows.at(-1),ema=emaSnapshot(rows)[period].value;return latest&&ema!=null?((num(latest.close)-ema)*side>0?82:28):50;});return scores.length?average(scores):50;},evaluate=direction=>{
      const side=sideValue(direction),last=primary.at(-1),first=primary.at(-9),stackPairs=[[9,21],[21,55],[55,100]],stack=average(stackPairs.map(([fast,slow])=>(primaryEma[fast].value-primaryEma[slow].value)*side>0?100:0));
      const slopes=average([9,21,55].map(period=>(primaryEma[period].value-primaryEma[period].prior)*side>0?100:0));
      const pressure=last&&first?clamp(50+(num(last.close)-num(first.open))*side/primaryAtr*18):0;
      const structure=alignment(structuralSets,direction,55),boundary=alignment(boundarySets,direction,100);
      const flow=candleFlow(primary,direction,8),acceptance=clamp(45+flow.priceProgressAtr*22+(flow.effective?20:0)-(flow.ineffectiveHighVolume?22:0));
      const phase=clamp((stack+slopes+structure)/3);const score=clamp(stack*.22+slopes*.13+pressure*.2+structure*.2+boundary*.08+acceptance*.1+phase*.07);
      return {direction,score,breakdown:{maStackOrder:stack,maSlopeAndTransition:slopes,primaryPressure:pressure,closedStructure:structure,higherTimeframeBoundaries:boundary,recentAcceptanceFailure:acceptance,phaseConsistency:phase},flow};
    };
    const long=evaluate("LONG"),short=evaluate("SHORT"),automaticWinner=long.score>=short.score?long:short,automaticRunner=automaticWinner===long?short:long,automaticPermission=automaticWinner.score>=58&&automaticWinner.score-automaticRunner.score>=5,mode=["LONG","SHORT"].includes(String(directionMode).toUpperCase())?String(directionMode).toUpperCase():"AUTO",selected=mode==="LONG"?long:mode==="SHORT"?short:automaticWinner,permission=mode==="AUTO"?automaticPermission:selected.score>=58;
    const earlyOpposite=candleFlow(closedRows(snapshot,profile.early),selected.direction==="LONG"?"SHORT":"LONG",6),lowerTimeframeWarning={active:earlyOpposite.effective,direction:selected.direction==="LONG"?"SHORT":"LONG",evidence:earlyOpposite.evidence},opposingAutomaticBias=mode!=="AUTO"&&automaticPermission&&automaticWinner.direction!==mode;
    return {direction:mode==="AUTO"?(permission?selected.direction:null):mode,directionMode:mode,score:selected.score,longScore:long.score,shortScore:short.score,permission,automaticDirection:automaticPermission?automaticWinner.direction:null,opposingAutomaticBias,opposingEvidence:opposingAutomaticBias?[`Automatic evidence favors ${automaticWinner.direction} ${automaticWinner.score.toFixed(0)} versus selected ${mode} ${selected.score.toFixed(0)}`]:[],breakdown:{...selected.breakdown,lowerTimeframeWarning},primaryFlow:selected.flow,lowerTimeframeWarning,reason:permission?`${selected.direction} permission from primary/structural agreement`:mode==="AUTO"?`Directional evidence is mixed (${long.score.toFixed(0)} LONG / ${short.score.toFixed(0)} SHORT)`:`${mode} selected manually; directional evidence is unsupported (${selected.score.toFixed(0)})`};
  }
  function triggerEvidence(snapshot,profile,direction,setup,volatility){
    const rows=closedRows(snapshot,profile.trigger),side=sideValue(direction),interactionTime=num(setup&&setup.interactionTime),interactionIndex=interactionTime==null?-1:rows.findIndex(row=>num(row.time)>=interactionTime),post=interactionIndex>=0?rows.slice(interactionIndex,interactionIndex+profile.eventWindow+2):[];
    const postAfter=post.slice(1),preShiftRows=rows.slice(Math.max(0,interactionIndex-4),Math.max(1,interactionIndex)),referenceRows=preShiftRows.length?preShiftRows:(post.length?[post[0]]:rows.slice(-1)),breakLevel=direction==="LONG"?Math.max(...referenceRows.map(row=>num(row.high))):Math.min(...referenceRows.map(row=>num(row.low)));
    const triggerAtr=atr(rows)||volatility.atr||1,shiftRow=postAfter.find(row=>(num(row.close)-breakLevel)*side>triggerAtr*.04),shiftIndex=shiftRow?rows.indexOf(shiftRow):-1,microstructureShift=!!shiftRow;
    const eventRows=post.length?post:rows.slice(-profile.eventWindow),flow=candleFlow(eventRows,direction,profile.eventWindow),participation=participationEvidence(rows,eventRows,direction);
    if(flow.absorption&&flow.effective)participation.credibleAbsorption=true;
    const rangeAtr=triggerAtr,displacement=postAfter.reduce((best,row)=>Math.max(best,(num(row.close)-num(row.open))*side/rangeAtr),0),wickHeavy=postAfter.some(row=>{const range=Math.max(1e-9,num(row.high)-num(row.low)),body=Math.abs(num(row.close)-num(row.open));return body/range<.32&&(num(row.close)-num(row.open))*side>0;});
    const displacementScore=clamp(displacement*85+(flow.priceProgressAtr>0?25:0)-(wickHeavy&&flow.priceProgressAtr<.3?25:0));
    let retestHeld=false;if(shiftIndex>=0){retestHeld=rows.slice(shiftIndex+1,shiftIndex+4).some(row=>direction==="LONG"?num(row.low)<=breakLevel+rangeAtr*.12&&num(row.close)>breakLevel:num(row.high)>=breakLevel-rangeAtr*.12&&num(row.close)<breakLevel);}
    const follow=shiftIndex>=0?rows.slice(shiftIndex,shiftIndex+4):[],qualifiedFollowThrough=follow.length>=2&&flow.priceProgressAtr>=.55&&follow.filter(row=>(num(row.close)-num(row.open))*side>0).length>=2&&!wickHeavy;
    const freshness=shiftRow?Math.max(0,rows.length-1-shiftIndex):Infinity,freshnessScore=Number.isFinite(freshness)?clamp(100-freshness*15):0;
    return {microstructureShift,shiftTime:shiftRow&&shiftRow.time||null,breakLevel,displacementQuality:displacementScore,wickHeavy,flow,participation,retestHeld,qualifiedFollowThrough,freshnessCandles:freshness,freshnessScore,eventWindow:{from:post[0]&&post[0].time||null,to:post.at(-1)&&post.at(-1).time||null,count:post.length},evidence:[microstructureShift?`Closed ${profile.trigger} post-interaction structure shift`:`No closed ${profile.trigger} post-interaction structure shift`,...flow.evidence]};
  }
  function oppositionEvidence(snapshot,profile,direction){
    const rows=closedRows(snapshot,profile.primary),flow=candleFlow(rows,direction==="LONG"?"SHORT":"LONG",8),emas=emaSnapshot(rows),side=sideValue(direction),opposingStack=[9,21,55].every((period,index,array)=>index===array.length-1||(emas[period].value-emas[array[index+1]].value)*side<0);
    const effective=(flow.effective&&flow.priceProgressAtr>=.35)||(opposingStack&&flow.priceProgressAtr>=.2);
    return {effective,evidence:effective?[`${profile.primary} opposing flow produced ${flow.priceProgressAtr.toFixed(2)} ATR progress`,...(opposingStack?[`${profile.primary} MA stack is effectively opposed`]:[])]:[],neutral:!effective};
  }
  function liveRows(snapshot,tf){return (snapshot&&snapshot.rowsByTf&&snapshot.rowsByTf[tf])||closedRows(snapshot,tf);}
  function formingRow(snapshot,tf){const rows=liveRows(snapshot,tf),last=rows.at(-1);return last&&last.final===false&&num(last.close)!=null?last:null;}
  function formingTriggerEvidence(snapshot,profile,direction){
    const closed=closedRows(snapshot,profile.trigger),forming=formingRow(snapshot,profile.trigger);
    if(!forming||closed.length<5)return {available:false,progress:0,imbalance:0};
    const side=sideValue(direction),rangeAtr=atr(closed)||1,volume=num(forming.volume)||0,buy=num(forming.takerBuyBase)||0;
    const progress=(num(forming.close)-num(forming.open))*side/rangeAtr,imbalance=volume>0?((buy-(volume-buy))/volume)*side:0;
    return {available:true,progress,imbalance};
  }
  function earlyAgreementEvidence(snapshot,profile,direction){
    const rows=liveRows(snapshot,profile.early).filter(row=>row&&num(row.close)!=null);
    if(rows.length<6)return {available:false,progress:0,closeShare:0};
    const flow=candleFlow(rows,direction,6);
    return {available:true,progress:flow.priceProgressAtr,closeShare:flow.directionalCloseShare};
  }
  function recentMomentumEvidence(snapshot,profile,direction){
    const closed=closedRows(snapshot,profile.trigger);
    if(closed.length<20)return {available:false,recentImbalance:0,priorImbalance:0};
    return {available:true,recentImbalance:candleFlow(closed,direction,4).directionalImbalance,priorImbalance:candleFlow(closed.slice(0,-4),direction,10).directionalImbalance};
  }
  function targetGeometry(snapshot,profile,direction,setup,trigger,volatility){
    const side=sideValue(direction),requiredTrigger=optionalNum(trigger&&trigger.breakLevel)??optionalNum(setup&&setup.level),rangeAtr=atr(setup&&setup.rows||[])||volatility.atr||1,allowance=rangeAtr*.08,projectedEntry=requiredTrigger==null?null:requiredTrigger+side*allowance,levels=[];
    [...profile.structures,...profile.boundaries].forEach(tf=>{const pivots=swingPoints(closedRows(snapshot,tf).slice(-120));(direction==="LONG"?pivots.highs:pivots.lows).forEach(point=>{if(requiredTrigger!=null&&(point.price-requiredTrigger)*side>0)levels.push({price:point.price,tf});});});
    levels.sort((a,b)=>(a.price-b.price)*side);const target=levels[0]||null,invalidation=optionalNum(setup&&setup.invalidation);
    if(requiredTrigger==null)return {target:target&&target.price||null,targetTimeframe:target&&target.tf||null,requiredTrigger:null,projectedEntry:null,riskDistance:null,grossReward:null,netReward:null,grossRr:null,netRr:null,viable:false,setupGeometryValid:false,feeSlippageAllowance:allowance,reason:"Required trigger is unavailable"};
    if(!target)return {target:null,targetTimeframe:null,requiredTrigger,projectedEntry,riskDistance:null,grossReward:null,netReward:null,grossRr:null,netRr:null,viable:false,setupGeometryValid:false,feeSlippageAllowance:allowance,reason:"No confirmed opposing structural target"};
    const grossReward=(target.price-projectedEntry)*side,riskDistance=(projectedEntry-invalidation)*side,netReward=grossReward-allowance,grossRr=riskDistance>0?grossReward/riskDistance:null,netRr=riskDistance>0&&netReward>0?netReward/(riskDistance+allowance):null,setupGeometryValid=(target.price-requiredTrigger)*side>0&&invalidation!=null&&(requiredTrigger-invalidation)*side>0&&grossReward>0&&riskDistance>0&&netReward>0;
    return {target:target.price,targetTimeframe:target.tf,requiredTrigger,projectedEntry,remainingDistance:grossReward,stopDistance:riskDistance,riskDistance,grossReward,netReward,grossRr,netRr,viable:setupGeometryValid&&netRr>=profile.minNetRr,setupGeometryValid,feeSlippageAllowance:allowance,reason:setupGeometryValid?null:`Invalid ${direction} geometry from required trigger`};
  }
  function extractFacts(snapshot,horizonId,state,directionMode="AUTO"){
    const profile=PROFILES[horizonId]||PROFILES.quick,direction=directionEvidence(snapshot,profile,directionMode),selectedDirection=direction.direction||((direction.longScore>=direction.shortScore)?"LONG":"SHORT"),primaryVolatility=volatilityEvidence(closedRows(snapshot,profile.primary)),candidates=setupCandidates(snapshot,profile,selectedDirection,primaryVolatility),setup=candidates[0]||null;
    if(setup){const identity=[snapshot.symbol,horizonId,selectedDirection,setup.family,setup.tf,Math.round(setup.level*1e6)/1e6].join("|");setup.identity=identity;const previous=state.setupHistories.get(identity)||{firstSeenVersion:snapshot.version,maxTests:0};previous.maxTests=Math.max(previous.maxTests,setup.repeatedTests);previous.lastSeenVersion=snapshot.version;state.setupHistories.set(identity,previous);while(state.setupHistories.size>128)state.setupHistories.delete(state.setupHistories.keys().next().value);setup.repeatedTests=previous.maxTests;}
    const trigger=setup?triggerEvidence(snapshot,profile,selectedDirection,setup,primaryVolatility):{microstructureShift:false,displacementQuality:0,flow:{effective:false,evidence:[]},participation:{state:"UNAVAILABLE",score:50,credibleAbsorption:false},retestHeld:false,qualifiedFollowThrough:false,freshnessScore:0,evidence:[]},opposition=oppositionEvidence(snapshot,profile,selectedDirection),geometry=setup?targetGeometry(snapshot,profile,selectedDirection,setup,trigger,primaryVolatility):{netRr:null,viable:false,setupGeometryValid:false};
    const price=num(snapshot.currentPrice),setupAtr=atr(setup&&setup.rows||[])||primaryVolatility.atr,originDistanceAtr=setup&&setupAtr?Math.max(0,Math.abs(price-setup.level)-((setup.zone.high-setup.zone.low)/2))/setupAtr:Infinity;
    const setupComponents={structuralLocation:setup?clamp(setup.quality+(setup.structural?8:0)-Math.max(0,setup.repeatedTests-2)*8):0,regimeAlignment:direction.permission?clamp(direction.score):25,eventLevelQuality:setup?setup.quality:0,invalidationTargetGeometry:geometry.viable?clamp(55+geometry.netRr*15):clamp(geometry.netRr*30),volatilitySuitability:primaryVolatility.regime==="Normal"?85:primaryVolatility.regime==="Expanding/controlled"?78:primaryVolatility.regime==="Compressed"?55:25};
    const fresh=String(snapshot&&snapshot.freshness&&snapshot.freshness.signalStatus||snapshot&&snapshot.health&&snapshot.health.status||"").toUpperCase();
    const timeframesUsed=unique([profile.early,profile.trigger,profile.primary,...profile.setups,...profile.structures,...profile.boundaries]),createdAt=num(snapshot&&snapshot.createdAt),ageMs=createdAt==null?null:Math.max(0,Date.now()-createdAt);
    const readinessSignals={formingTrigger:formingTriggerEvidence(snapshot,profile,selectedDirection),early:earlyAgreementEvidence(snapshot,profile,selectedDirection),momentum:recentMomentumEvidence(snapshot,profile,selectedDirection)};
    return {fresh:["LIVE","SUFFICIENT"].includes(fresh),directionalPermission:direction,setup:setup?{...setup,setupPresent:true,qualityAcceptable:setup.quality>=60}:null,setupCandidates:candidates.map(item=>({family:item.family,tf:item.tf,quality:item.quality,distanceAtr:item.distanceAtr,interacted:item.interacted,nonEma:item.nonEma})),setupComponents,trigger,opposition,volatility:primaryVolatility,geometry,current:{price,originDistanceAtr,chased:originDistanceAtr>profile.chaseAtr,adverseEvidenceStrength:opposition.effective?70:15,adverseEvidenceSafety:opposition.effective?30:85},data:{timeframesUsed,freshness:fresh||"UNAVAILABLE",ageMs,componentAvailability:{lowerTimeframeWarning:direction.lowerTimeframeWarning?"AVAILABLE":"UNAVAILABLE"}},profile,readinessSignals};
  }
  const optionalNum=value=>value==null||value===""?null:num(value);
  function displayPrice(value){const n=optionalNum(value);if(n==null)return "unavailable";const parts=(Number.isInteger(n)?String(n):n.toFixed(6).replace(/0+$/g,"").replace(/\.$/,"")).split(".");parts[0]=parts[0].replace(/\B(?=(\d{3})+(?!\d))/g,",");return parts.join(".");}
  function evaluateSetupGeometry(direction,setup,trigger,geometry,profile){
    const side=sideValue(direction),requiredTrigger=optionalNum(geometry.requiredTrigger)??optionalNum(trigger.breakLevel)??optionalNum(setup&&setup.trigger)??optionalNum(setup&&setup.level),target=optionalNum(geometry.target)??optionalNum(setup&&setup.target),invalidation=optionalNum(geometry.invalidation)??optionalNum(setup&&setup.invalidation),allowance=Math.max(0,optionalNum(geometry.feeSlippageAllowance)||0),projectedEntry=optionalNum(geometry.projectedEntry)??(requiredTrigger==null?null:requiredTrigger+side*allowance);
    const legacy=requiredTrigger==null||target==null||invalidation==null;
    if(legacy){const netRr=num(geometry.netRr),setupGeometryValid=geometry.setupGeometryValid===true||(geometry.viable===true&&netRr!=null&&netRr>0),viableNetRewardRisk=setupGeometryValid&&geometry.viable===true&&netRr>=profile.minNetRr;return {...geometry,requiredTrigger,projectedEntry,target,invalidation,setupGeometryValid,viableNetRewardRisk,netRr:setupGeometryValid?netRr:null,rrStatus:viableNetRewardRisk?"VALID":"INVALID",reason:geometry.reason||(!requiredTrigger?"Required trigger is unavailable":!target?"Directional target is unavailable":"Invalidation is unavailable"),stateReason:geometry.reason||`No valid ${direction} setup: executable geometry is unavailable.`};}
    const targetProgress=(target-requiredTrigger)*side,invalidationRoom=(requiredTrigger-invalidation)*side,grossReward=(target-projectedEntry)*side,riskDistance=(projectedEntry-invalidation)*side,netReward=grossReward-allowance;
    let reason=null,stateReason=null;
    if(!(targetProgress>0)){reason=`Invalid ${direction} geometry: target ${displayPrice(target)} is ${direction==="LONG"?"below":"above"} required trigger ${displayPrice(requiredTrigger)}.`;stateReason=`No valid ${direction} setup: target ${displayPrice(target)} is ${direction==="LONG"?"below":"above"} required trigger ${displayPrice(requiredTrigger)}.`;}
    else if(!(invalidationRoom>0)){reason=`Invalid ${direction} geometry: invalidation ${displayPrice(invalidation)} is ${direction==="LONG"?"above":"below"} required trigger ${displayPrice(requiredTrigger)}.`;stateReason=`No valid ${direction} setup: invalidation ${displayPrice(invalidation)} is ${direction==="LONG"?"above":"below"} required trigger ${displayPrice(requiredTrigger)}.`;}
    else if(!(grossReward>0&&riskDistance>0&&netReward>0)){reason=`Invalid ${direction} geometry: projected executable entry leaves no positive net reward or risk distance.`;stateReason=`No valid ${direction} setup: projected executable entry leaves no positive net reward or risk distance.`;}
    const setupGeometryValid=!reason,netRr=setupGeometryValid?netReward/(riskDistance+allowance):null,viableNetRewardRisk=setupGeometryValid&&netRr>=profile.minNetRr;
    if(setupGeometryValid&&!viableNetRewardRisk){reason=`Net reward/risk ${netRr.toFixed(2)} is below required ${profile.minNetRr.toFixed(2)}.`;stateReason=`No valid ${direction} setup: estimated net RR ${netRr.toFixed(2)} is below required ${profile.minNetRr.toFixed(2)}.`;}
    return {...geometry,requiredTrigger,projectedEntry,target,invalidation,grossReward,riskDistance,netReward,netRr,setupGeometryValid,viableNetRewardRisk,rrStatus:viableNetRewardRisk?"VALID":"INVALID",reason,stateReason};
  }
  function availabilityMissing(facts,permission){
    const components={...(facts.componentAvailability||{}),...(facts.data&&facts.data.componentAvailability||{})};
    if(String(permission.lowerTimeframeWarning||permission.breakdown&&permission.breakdown.lowerTimeframeWarning||"").toUpperCase()==="UNAVAILABLE"&&!Object.prototype.hasOwnProperty.call(components,"lowerTimeframeWarning"))components.lowerTimeframeWarning="UNAVAILABLE";
    return Object.entries(components).filter(([,value])=>value===false||value&&typeof value==="object"&&value.available===false||["UNAVAILABLE","MISSING"].includes(String(value||"").toUpperCase())).map(([name])=>name);
  }
  function partitionGates(statuses){const passed=[],failed=[],pending=[];Object.entries(statuses).forEach(([name,status])=>{(status==="passed"?passed:status==="pending"?pending:failed).push(name);});return {passed,failed,pending};}
  function readinessGateProgress(gateStatuses,activationGateNames){
    const total=activationGateNames.length;
    if(!total)return 0;
    const sum=activationGateNames.reduce((accumulator,name)=>accumulator+(gateStatuses[name]==="passed"?1:gateStatuses[name]==="pending"?.5:0),0);
    return clamp(sum/total*100);
  }
  function readinessBonuses(signals={}){
    const forming=signals.formingTrigger||{},early=signals.early||{},momentum=signals.momentum||{};
    const formingBonus=forming.available&&forming.progress>0&&forming.imbalance>0?Math.min(1,(Math.min(forming.progress,1)+Math.min(forming.imbalance,1))/2)*12:0;
    const earlyBonus=early.available&&early.progress>0&&(early.closeShare??0)>=.5?Math.min(1,early.progress)*8:0;
    const momentumDelta=momentum.available?momentum.recentImbalance-momentum.priorImbalance:0;
    const momentumBonus=momentum.available&&momentumDelta>0&&momentum.recentImbalance>0?Math.min(1,momentumDelta*4)*6:0;
    return formingBonus+earlyBonus+momentumBonus;
  }
  function computeReadinessScore(stateName,gateStatuses,activationGateNames,setupScore,triggerScore,signals){
    if(stateName==="TRIGGER ACTIVE")return 100;
    const gateProgress=readinessGateProgress(gateStatuses,activationGateNames);
    const base=gateProgress*.5+clamp(triggerScore)*.2+clamp(setupScore)*.15;
    return clamp(base+readinessBonuses(signals));
  }
  function applySetupLifecycle(facts,state){const setup=facts&&facts.setup,identity=setup&&setup.identity;if(!identity)return facts;const history=state.setupHistories.get(identity)||{firstSeenVersion:null,maxTests:0,everValid:false,terminalInvalidated:false};const nextSetup={...setup};if(history.terminalInvalidated){nextSetup.invalidated=true;nextSetup.previouslyValid=true;}else if(nextSetup.invalidated&&history.everValid)nextSetup.previouslyValid=true;return {...facts,setup:nextSetup};}
  function recordSetupLifecycle(facts,result,state){const setup=facts&&facts.setup,identity=setup&&setup.identity;if(!identity)return;const history=state.setupHistories.get(identity)||{firstSeenVersion:null,maxTests:0,everValid:false,terminalInvalidated:false};history.everValid=history.everValid||result&&result.comparisonDiagnostics&&result.comparisonDiagnostics.validSetup===true;history.terminalInvalidated=history.terminalInvalidated||setup.invalidated===true&&(history.everValid||setup.previouslyValid===true||setup.valid===true);history.maxTests=Math.max(Number(history.maxTests)||0,Number(setup.repeatedTests)||0);state.setupHistories.set(identity,history);}
  function scoreFacts(facts,{horizonId="quick",symbol="",version=0,directionMode="AUTO"}={}){
    const profile=facts.profile||PROFILES[horizonId]||PROFILES.quick,permission=facts.directionalPermission||{},mode=["LONG","SHORT"].includes(String(directionMode).toUpperCase())?String(directionMode).toUpperCase():"AUTO",publishedDirection=mode==="AUTO"?(permission.direction||"NO BIAS"):mode,rawSetup=facts.setup,setup=rawSetup&&(!rawSetup.direction||rawSetup.direction===publishedDirection)?rawSetup:null,trigger=facts.trigger||{},flow=trigger.flow||{},participation=trigger.participation||{},geometry=facts.geometry||{},volatility=facts.volatility||{},current=facts.current||{};
    const sc=facts.setupComponents||{},setupBreakdown={structuralLocation:clamp(sc.structuralLocation),regimeAlignment:clamp(sc.regimeAlignment),eventLevelQuality:clamp(sc.eventLevelQuality),invalidationTargetGeometry:clamp(sc.invalidationTargetGeometry),volatilitySuitability:clamp(sc.volatilitySuitability)};
    const setupScore=clamp(setupBreakdown.structuralLocation*.30+setupBreakdown.regimeAlignment*.25+setupBreakdown.eventLevelQuality*.20+setupBreakdown.invalidationTargetGeometry*.15+setupBreakdown.volatilitySuitability*.10);
    const triggerBreakdown={postInteractionMicrostructure:trigger.microstructureShift?100:0,reactionDisplacement:clamp(trigger.displacementQuality),directionalFlowEffectiveness:flow.effective?clamp(70+(flow.priceProgressAtr||0)*25-(flow.ineffectiveHighVolume?35:0)):clamp((flow.priceProgressAtr||0)*25),participationPersistence:clamp(participation.score??50),retestFollowThroughFreshness:clamp((trigger.retestHeld?100:trigger.qualifiedFollowThrough?82:0)*.75+(trigger.freshnessScore||0)*.25)};
    const triggerScore=clamp(triggerBreakdown.postInteractionMicrostructure*.25+triggerBreakdown.reactionDisplacement*.20+triggerBreakdown.directionalFlowEffectiveness*.25+triggerBreakdown.participationPersistence*.15+triggerBreakdown.retestFollowThroughFreshness*.15);
    const geometryEvaluation=evaluateSetupGeometry(publishedDirection,setup,trigger,geometry,profile),setupPresent=!!setup,setupQualityAcceptable=setupPresent&&setupScore>=60,setupGeometryValid=setupPresent&&geometryEvaluation.setupGeometryValid===true,viableNetRewardRisk=setupGeometryValid&&geometryEvaluation.viableNetRewardRisk===true,validSetup=setupPresent&&setupQualityAcceptable&&setupGeometryValid&&viableNetRewardRisk;
    const directionalProgress=num(flow.directionalProgressAtr)??num(flow.priceProgressAtr),directionalCloseShare=num(flow.directionalCloseShare)??(flow.effective===true?1:flow.effective===false?0:null),displacementAvailable=directionalProgress!=null&&directionalCloseShare!=null,progressiveDisplacement=displacementAvailable&&directionalProgress>=.28&&directionalCloseShare>=.5&&clamp(trigger.displacementQuality)>=25&&!(trigger.wickHeavy===true&&directionalProgress<.3),effectiveFlow=flow.effective===true&&flow.ineffectiveHighVolume!==true&&directionalProgress!=null&&directionalProgress>0&&directionalCloseShare>=.5;
    const distanceScore=clamp(100-(num(current.originDistanceAtr)??profile.chaseAtr*2)/profile.chaseAtr*100),rewardScore=geometryEvaluation.viableNetRewardRisk?clamp((num(geometryEvaluation.netRr)||0)/Math.max(profile.minNetRr,1)*75):0,adverseEvidenceSafety=clamp(num(current.adverseEvidenceSafety)??(100-(num(current.adverseEvidenceStrength)??num(current.adverseEvidence)??0))),persistenceScore=clamp(num(current.volatilityParticipationPersistence)??((participation.score??50)+(volatility.controlledAcceptance===false?15:85))/2);
    const currentBreakdown={triggerCredibility:triggerScore,distanceFromOrigin:distanceScore,remainingRoomNetRewardRisk:rewardScore,adverseEvidenceSafety,volatilityParticipationPersistence:persistenceScore};
    const currentScore=clamp(currentBreakdown.triggerCredibility*.30+currentBreakdown.distanceFromOrigin*.25+currentBreakdown.remainingRoomNetRewardRisk*.25+currentBreakdown.adverseEvidenceSafety*.10+currentBreakdown.volatilityParticipationPersistence*.10);
    const weakParticipationAllowed=participation.state!=="WEAK"||(participation.credibleAbsorption===true&&effectiveFlow),setupNotWeakened=!(setup&&setup.repeatedTests>=4),previouslyValid=!!setup&&(setup.previouslyValid===true||setup.valid===true||setupQualityAcceptable&&setupGeometryValid&&viableNetRewardRisk),oppositionClear=!facts.opposition||facts.opposition.effective!==true,controlledVolatility=volatility.regime!=="Disorderly/extreme"||volatility.controlledAcceptance===true;
    const status=(value,pending=false)=>pending?"pending":value?"passed":"failed",gateStatuses={
      freshData:status(facts.fresh===true),directionalPermission:status(permission.permission===true&&publishedDirection!=="NO BIAS"),setupPresent:status(setupPresent),setupQualityAcceptable:status(setupQualityAcceptable,!setupPresent),setupGeometryValid:status(setupGeometryValid,!setupPresent),viableNetRewardRisk:status(viableNetRewardRisk,!setupPresent),validSetup:status(validSetup,!setupPresent),
      setupInteraction:status(setup&&setup.interacted===true,!validSetup),closedReaction:status(setup&&setup.reactionConfirmed===true,!validSetup||!setup.interacted),postInteractionShift:status(trigger.microstructureShift===true,!validSetup||!setup.reactionConfirmed),effectiveFlow:status(effectiveFlow,!validSetup&&!displacementAvailable),retestOrQualifiedFollowThrough:status(trigger.retestHeld===true||trigger.qualifiedFollowThrough===true,!validSetup||!trigger.microstructureShift),
      noEffectivePrimaryOpposition:status(oppositionClear),currentEntryAtLeastB:status(currentScore>=70,!validSetup||!trigger.microstructureShift),notChased:status(current.chased!==true,!validSetup),participationConviction:status(weakParticipationAllowed),controlledVolatility:status(controlledVolatility),progressiveDisplacement:status(progressiveDisplacement,!displacementAvailable),setupNotWeakened:status(setupNotWeakened,!setupPresent)
    };
    const hardGates=partitionGates(gateStatuses),activationGateNames=["freshData","directionalPermission","validSetup","setupInteraction","closedReaction","postInteractionShift","effectiveFlow","retestOrQualifiedFollowThrough","noEffectivePrimaryOpposition","currentEntryAtLeastB","viableNetRewardRisk","notChased","participationConviction","controlledVolatility","progressiveDisplacement","setupNotWeakened"],allActive=activationGateNames.every(name=>gateStatuses[name]==="passed"),triggerCoreValid=["closedReaction","postInteractionShift","effectiveFlow","retestOrQualifiedFollowThrough","progressiveDisplacement","participationConviction","controlledVolatility","setupNotWeakened"].every(name=>gateStatuses[name]==="passed");
    let stateReason,stateName;
    if(!permission.permission){stateName="NO SETUP";stateReason=permission.reason||"Directional permission is unavailable";}
    else if(setup&&setup.invalidated&&previouslyValid){stateName="SETUP FAILED";stateReason="Closed structural invalidation breached the previously valid setup";}
    else if(!setupPresent){stateName="NO SETUP";stateReason="No structural setup candidate is present";}
    else if(setup.invalidated){stateName="NO SETUP";stateReason=`No valid ${publishedDirection} setup: the candidate was invalidated before becoming valid.`;}
    else if(!setupGeometryValid||!viableNetRewardRisk){stateName="NO SETUP";stateReason=geometryEvaluation.stateReason||`No valid ${publishedDirection} setup: executable geometry is not tradable.`;}
    else if(!setupQualityAcceptable){stateName="WATCHING";stateReason=`${setup.family||"Candidate setup"} is present, but Setup Quality ${setupScore.toFixed(0)} is below the minimum 60.`;}
    else if(triggerCoreValid&&current.chased){stateName="NO CHASE";stateReason=`Valid trigger is ${Number(current.originDistanceAtr).toFixed(2)} ATR from origin`;}
    else if(allActive){stateName="TRIGGER ACTIVE";stateReason="Closed reaction, post-interaction shift, effective flow and entry-efficiency gates all passed";}
    else if(setup.reactionConfirmed||trigger.microstructureShift||directionalProgress!=null&&Math.abs(directionalProgress)>=.1){stateName="TRIGGER FORMING";stateReason=`Trigger evidence is developing; pending or failed confirmation gates: ${[...hardGates.failed,...hardGates.pending].filter(name=>!["setupPresent","setupQualityAcceptable","setupGeometryValid","validSetup","viableNetRewardRisk"].includes(name)).join(", ")}`;}
    else{stateName="STAND BY";stateReason="Valid setup and viable geometry are present; trigger confirmation gates remain pending";}
    const presentation=PRESENTATION[stateName],direction=publishedDirection,triggerIdentity=stateName==="TRIGGER ACTIVE"?[symbol,horizonId,direction,setup.identity,profile.trigger,trigger.shiftTime||version].join("|"):null;
    const adverseEvidence=unique([...(permission.opposingEvidence||[]),directionalProgress!=null&&directionalProgress<.28&&`Price progress ${directionalProgress.toFixed(2)} ATR ${directionalProgress<0?`against ${direction}`:`below the ${direction} displacement minimum`}.`,directionalCloseShare!=null&&directionalCloseShare<.5&&`Directional closes ${(directionalCloseShare*100).toFixed(0)}%.`,setup&&!setup.reactionConfirmed&&`No closed ${profile.trigger} reaction.`,trigger.microstructureShift!==true&&"No post-interaction structure shift.",!effectiveFlow&&flow.directionalImbalance>0&&"Ineffective directional flow; positive taker imbalance did not produce matching price progress.",!effectiveFlow&&!(flow.directionalImbalance>0)&&"No effective directional flow.",participation.state==="WEAK"&&"Weak participation.",!setupNotWeakened&&"Setup weakened by repeated material tests.",geometryEvaluation.reason,...(facts.opposition&&facts.opposition.evidence||[])]),supportingEvidence=unique([permission.reason,effectiveFlow&&progressiveDisplacement&&"Effective directionally progressive flow",setup&&setup.reactionConfirmed&&`Closed ${profile.trigger} reaction`,trigger.microstructureShift&&`Closed ${profile.trigger} post-interaction structure shift`,(trigger.retestHeld||trigger.qualifiedFollowThrough)&&"Retest or qualified follow-through confirmed"]),secondaryReasons=unique([!setupQualityAcceptable&&setupPresent&&"Setup Quality below minimum.",!viableNetRewardRisk&&setupPresent&&"Net RR invalid or unviable.",...adverseEvidence]),reasons=unique([stateReason,...secondaryReasons]),exclusions=[...hardGates.failed.map(name=>`Hard gate failed: ${name}`),...hardGates.pending.map(name=>`Hard gate pending: ${name}`)];
    const decision={state:presentation.internal,reason:stateReason,secondaryReasons,direction,setupIdentity:setup&&setup.identity||null,family:setup&&setup.family||null,tf:setup&&setup.tf||null,horizonId,triggerIdentity,triggerState:stateName==="TRIGGER ACTIVE"?"active":stateName==="TRIGGER FORMING"?"developing":"absent",setupPresent,setupQualityAcceptable,setupGeometryValid,viableNetRewardRisk,validSetup,progressiveDisplacement,setupNotWeakened,gateStatuses:{...gateStatuses},interaction:{interactionTime:setup&&setup.interactionTime||null,reactionTime:setup&&setup.reactionConfirmed?setup.interactionTime:null,evidence:trigger.evidence||[]},pressure:{triggerTf:profile.trigger,primaryTf:profile.primary,evidence:flow.evidence||[],effectiveOpposition:facts.opposition&&facts.opposition.effective===true},assessments:{setup:{score:setupScore,grade:GRADE(setupScore)},trigger:{score:triggerScore,grade:GRADE(triggerScore)},current:{score:currentScore,grade:GRADE(currentScore)}}};
    const currentPrice=optionalNum(current.price),triggerLevel=optionalNum(geometryEvaluation.requiredTrigger)??optionalNum(trigger.breakLevel)??optionalNum(setup&&setup.level),relativeDelta=currentPrice==null||triggerLevel==null?null:(currentPrice-triggerLevel)*sideValue(direction);
    const setupEvidence=setup?{family:setup.family||null,timeframe:setup.tf||null,level:num(setup.level),zone:setup.zone||null,structural:setup.structural===true,nonEma:setup.nonEma===true,repeatedTests:num(setup.repeatedTests),interacted:setup.interacted===true,reactionConfirmed:setup.reactionConfirmed===true,event:(setup.family||"Setup")+(setup.interacted?" interaction active":" awaiting interaction"),regimeAlignment:`${profile.primary||"UNAVAILABLE"} primary / ${setup.tf||"UNAVAILABLE"} setup`,invalidation:num(geometryEvaluation.invalidation),target:num(geometryEvaluation.target),targetTimeframe:geometryEvaluation.targetTimeframe||null,targetAvailable:num(geometryEvaluation.target)!=null,setupPresent,setupQualityAcceptable,setupGeometryValid,validSetup}:null;
    const triggerDiagnostics={microstructureShift:trigger.microstructureShift===true,reactionConfirmed:setup?setup.reactionConfirmed===true:null,displacementQuality:num(trigger.displacementQuality),flowEffective:flow.effective===true,flowEvidence:flow.evidence||[],participationPersistence:num(participation.persistence),retestHeld:trigger.retestHeld===true,qualifiedFollowThrough:trigger.qualifiedFollowThrough===true,freshnessCandles:num(trigger.freshnessCandles)};
    const entryCondition={triggerLevel,projectedExecutableEntry:num(geometryEvaluation.projectedEntry),zone:setup&&setup.zone||null,currentPrice,currentRelative:relativeDelta==null?null:relativeDelta===0?"AT TRIGGER":relativeDelta>0?`BEYOND BY ${relativeDelta.toFixed(6)}`:`BEFORE BY ${Math.abs(relativeDelta).toFixed(6)}`,invalidation:num(geometryEvaluation.invalidation),target:num(geometryEvaluation.target),targetTimeframe:geometryEvaluation.targetTimeframe||null,geometryReason:geometryEvaluation.reason||null};
    const data={timeframesUsed:facts.data&&facts.data.timeframesUsed||unique([profile.early,profile.trigger,profile.primary,...(profile.setups||[]),...(profile.structures||[]),...(profile.boundaries||[])]),freshness:facts.data&&facts.data.freshness||(facts.fresh?"LIVE":"STALE"),ageMs:optionalNum(facts.data&&facts.data.ageMs),componentAvailability:{...(facts.componentAvailability||{}),...(facts.data&&facts.data.componentAvailability||{})},missing:unique([!setup&&"setup location",triggerLevel==null&&"trigger level",currentPrice==null&&"current price",optionalNum(geometryEvaluation.invalidation)==null&&"invalidation",optionalNum(geometryEvaluation.target)==null&&"target",geometryEvaluation.rrStatus==="INVALID"&&"net reward/risk",...availabilityMissing(facts,permission)])};
    const readinessScore=computeReadinessScore(stateName,gateStatuses,activationGateNames,setupScore,triggerScore,facts.readinessSignals);
    const comparisonDiagnostics={directionMode:mode,automaticDirection:permission.automaticDirection||null,opposingAutomaticEvidence:permission.opposingEvidence||[],directionalPermissionScore:num(permission.score),directionalPermissionBreakdown:permission.breakdown||{},setupPresent,setupQualityAcceptable,setupGeometryValid,viableNetRewardRisk,validSetup,progressiveDisplacement,setupNotWeakened,setupScore,setupBreakdown,triggerScore,triggerBreakdown,currentEntryScore:currentScore,currentEntryBreakdown:currentBreakdown,hardGates,supportingEvidence,effectiveOppositionEvidence:adverseEvidence,volatilityRegime:volatility.regime||"Unavailable",realizedRangePercentile:num(volatility.realizedRangePercentile),participationState:participation.state||"UNAVAILABLE",participation,flowEffectiveness:{...flow,directionNormalizedProgressAtr:directionalProgress,directionalCloseShare,effective:effectiveFlow,progressiveDisplacement},chaseDistanceAtr:num(current.originDistanceAtr),remainingRewardRisk:geometryEvaluation.viableNetRewardRisk?num(geometryEvaluation.netRr):"INVALID",rewardRiskStatus:geometryEvaluation.rrStatus,setupEvidence,triggerEvidence:triggerDiagnostics,entryCondition,data,finalStateReason:stateReason,secondaryStateReasons:secondaryReasons,engineVersion:VERSION,publicationGeneration:null,readinessScore};
    return {direction,confidence:direction==="NO BIAS"?null:Math.round(num(permission.score)||0),entryState:stateName,setupIdentity:setup&&setup.identity||null,setupFamily:setup&&setup.family||null,setupTimeframe:setup&&setup.tf||null,setupPresent,setupQualityAcceptable,setupGeometryValid,viableNetRewardRisk,validSetup,progressiveDisplacement,setupNotWeakened,estimatedNetRewardRisk:comparisonDiagnostics.remainingRewardRisk,setupQuality:GRADE(setupScore),triggerQuality:GRADE(triggerScore),currentEntryQuality:GRADE(currentScore),entryVerdict:stateName==="TRIGGER ACTIVE"?`READY ${direction}`:"WAIT",reasons,exclusions,triggerIdentity,triggerEvidence:[...(trigger.evidence||[])],dataStatus:facts.fresh?"sufficient":"stale",tone:presentation.tone,visibleState:stateName,definition:presentation.definition,decision,comparisonDiagnostics,readinessScore};
  }
  function createState(){return {evidenceByTf:new Map(),smcCache:new Map(),entryTrackers:new Map(),setupHistories:new Map(),seenTriggerAlertIds:new Set(),seenTriggerAlertOrder:[],evaluationCache:new Map(),fingerprints:new Map()};}
  function clearState(state){Object.values(state).forEach(value=>{if(value instanceof Map||value instanceof Set)value.clear();else if(Array.isArray(value))value.length=0;});}
  function createSignalEngineB(){
    const state=createState();let calculations=0,cacheHits=0,activations=0,deactivations=0,lastDiagnostics=null;
    const engine={
      id:"B",displayName:"Refined blend",version:VERSION,status:"available",state,
      getRequirements(context={}){const horizonId=PROFILES[context.horizonId]?context.horizonId:"quick",profile=PROFILES[horizonId],slots=typeof context.getCanonicalSlots==="function"?context.getCanonicalSlots():[9,21,55,100,200].map((period,index)=>({slotId:`MA${index+1}`,period})),timeframes=unique([profile.early,profile.trigger,profile.primary,...profile.setups,...profile.structures,...profile.boundaries]);const items=timeframes.map(tf=>({tf,historyTarget:DEPTHS[tf]||320,roles:unique([tf===profile.early&&`${tf} early warning`,tf===profile.trigger&&`${tf} post-interaction trigger`,tf===profile.primary&&`${tf} primary direction`,profile.setups.includes(tf)&&`${tf} setup location`,profile.structures.includes(tf)&&`${tf} closed structure`,profile.boundaries.includes(tf)&&`${tf} higher-timeframe boundary`]),signalRequired:true,managementRequired:false}));return {horizonId,engine:{id:"B",profile},slots,items,timeframes};},
      evaluate(context={}){const snapshot=context.snapshot;if(!snapshot)throw new Error("Signal B market snapshot is unavailable");const horizonId=PROFILES[context.horizonId]?context.horizonId:"quick",directionMode=["LONG","SHORT"].includes(String(context.directionMode||"AUTO").toUpperCase())?String(context.directionMode).toUpperCase():"AUTO",fingerprint=[snapshot.signature||snapshot.version,horizonId,directionMode].join("|"),publicationGeneration=Number(context.publicationGeneration)||0;if(state.evaluationCache.has(fingerprint)){cacheHits+=1;const cached=state.evaluationCache.get(fingerprint);cached.comparisonDiagnostics.publicationGeneration=publicationGeneration;lastDiagnostics=cached.comparisonDiagnostics;return cached;}calculations+=1;const facts=applySetupLifecycle(extractFacts(snapshot,horizonId,state,directionMode),state),result=scoreFacts(facts,{horizonId,symbol:snapshot.symbol,version:snapshot.version,directionMode});recordSetupLifecycle(facts,result,state);result.comparisonDiagnostics.publicationGeneration=publicationGeneration;lastDiagnostics=result.comparisonDiagnostics;state.evaluationCache.set(fingerprint,result);state.fingerprints.set(`${horizonId}|${directionMode}`,fingerprint);while(state.evaluationCache.size>24)state.evaluationCache.delete(state.evaluationCache.keys().next().value);return result;},
      evaluateFacts(facts,metadata={}){const prepared=applySetupLifecycle(facts,state),result=scoreFacts(prepared,metadata);recordSetupLifecycle(prepared,result,state);result.comparisonDiagnostics.publicationGeneration=Number(metadata.publicationGeneration)||null;return result;},extractFacts(snapshot,horizonId="quick",directionMode="AUTO"){return extractFacts(snapshot,horizonId,state,directionMode);},
      onActivate(){activations+=1;},onDeactivate(){deactivations+=1;clearState(state);},reset(){clearState(state);},
      diagnostics(){return {calculations,cacheHits,activations,deactivations,cacheCounts:{evidenceByTf:state.evidenceByTf.size,setupHistories:state.setupHistories.size,evaluationCache:state.evaluationCache.size,fingerprints:state.fingerprints.size},lastPublication:lastDiagnostics,tuning:{directionalPermission:{minimum:58,minimumWinnerMargin:5},setupWeights:{structuralLocation:.30,regimeAlignment:.25,eventLevelQuality:.20,invalidationTargetGeometry:.15,volatilitySuitability:.10},triggerWeights:{postInteractionMicrostructure:.25,reactionDisplacement:.20,directionalFlowEffectiveness:.25,participationPersistence:.15,retestFollowThroughFreshness:.15},currentEntryWeights:{triggerCredibility:.30,distanceFromOrigin:.25,remainingRoomNetRewardRisk:.25,adverseEvidenceSafety:.10,volatilityParticipationPersistence:.10},gradeBands:{A:80,B:70,C:60},maximumMaterialTests:3,feeSlippageAllowanceAtr:.08,profiles:PROFILES}};}
    };return engine;
  }

  Object.defineProperty(window,"createSignalEngineB",{value:createSignalEngineB,configurable:true});
})();
