"use strict";
const assert=require("assert");
const fs=require("fs");
const path=require("path");
const vm=require("vm");

const root=path.resolve(__dirname,"..","..","..");
function runtime(){
  const context={console,Map,Set,Array,Object,String,Number,Boolean,Date,Promise,JSON,Math,Error,TypeError,AbortController};context.window=context;context.document={querySelector:()=>null};
  vm.createContext(context);for(const file of ["features/pressure-signal/engines/registry.js","features/pressure-signal/engines/engine-a.js","features/pressure-signal/engines/engine-b.js","features/pressure-signal/engines/selector.js","features/pressure-signal/ui/signal-tooltip.js"])vm.runInContext(fs.readFileSync(path.join(root,file),"utf8"),context,{filename:file});return context;
}
function merge(base,patch){const output=Array.isArray(base)?[...base]:{...base};for(const [key,value] of Object.entries(patch||{}))output[key]=value&&typeof value==="object"&&!Array.isArray(value)&&base&&base[key]&&typeof base[key]==="object"&&!Array.isArray(base[key])?merge(base[key],value):value;return output;}
function baseFacts(){return {
  fresh:true,profile:{early:"1m",trigger:"3m",primary:"5m",setups:["3m","5m"],structures:["15m","1h"],boundaries:["4h","1d"],eventWindow:7,chaseAtr:1.35,minNetRr:1.35},
  directionalPermission:{permission:true,direction:"LONG",score:84,longScore:84,shortScore:31,reason:"LONG primary/structural permission",breakdown:{maStackOrder:90,maSlopeAndTransition:82,primaryPressure:80,closedStructure:86}},
  setup:{valid:true,identity:"BTCUSDT|quick|LONG|structural-retest",family:"Structural retest",tf:"5m",interacted:true,interactionTime:120,reactionConfirmed:true,invalidated:false,repeatedTests:1,nonEma:true},
  setupComponents:{structuralLocation:90,regimeAlignment:86,eventLevelQuality:84,invalidationTargetGeometry:82,volatilitySuitability:85},
  trigger:{microstructureShift:true,shiftTime:180,displacementQuality:88,wickHeavy:false,flow:{effective:true,absorption:false,ineffectiveHighVolume:false,directionalImbalance:.18,priceProgressAtr:.72,efficiency:1.1,evidence:["Effective directional flow"]},participation:{state:"STRONG",score:88,credibleAbsorption:false,persistence:.75},retestHeld:true,qualifiedFollowThrough:false,freshnessScore:92,evidence:["Closed post-interaction structure shift","Effective directional flow"]},
  opposition:{effective:false,evidence:[],neutral:true},volatility:{regime:"Expanding/controlled",controlledAcceptance:true,realizedRangePercentile:78},geometry:{netRr:2.1,viable:true},current:{originDistanceAtr:.22,chased:false,adverseEvidence:10}
};}
function rows(tf,count=260,side=1){const seconds={"1m":60,"3m":180,"5m":300,"15m":900,"1h":3600,"4h":14400,"1d":86400}[tf],start=1700000000,rows=[];let price=40000;for(let index=0;index<count;index+=1){const wave=Math.sin(index/7)*8,move=side*(3+(index%5===0?2:0))+wave*.08,open=price,close=open+move,high=Math.max(open,close)+5,low=Math.min(open,close)-5,volume=100+(index%11)*4;rows.push({time:start+index*seconds,openTime:(start+index*seconds)*1000,closeTime:(start+(index+1)*seconds)*1000-1,open,high,low,close,volume,quoteVolume:volume*close,tradeCount:80+index%17,takerBuyBase:volume*(side>0?.57:.43),final:true});price=close;}return rows;}
function memoryStorage(){const data=new Map();return {getItem:key=>data.get(key)||null,setItem:(key,value)=>data.set(key,String(value))};}

const run=(async()=>{
  const context=runtime(),engine=context.createSignalEngineB();let caseSequence=0;const evaluate=(patch={},metadata={})=>{const facts=merge(baseFacts(),patch);facts.setup={...facts.setup,identity:patch.setup&&patch.setup.identity||`BTCUSDT|quick|LONG|case-${++caseSequence}`};return engine.evaluateFacts(facts,{horizonId:"quick",symbol:"BTCUSDT",version:7,...metadata});};
  const scenarios={};
  scenarios.cleanContinuation=evaluate();assert.equal(scenarios.cleanContinuation.entryState,"TRIGGER ACTIVE");
  scenarios.highVolumeNoProgress=evaluate({trigger:{flow:{effective:false,ineffectiveHighVolume:true,directionalImbalance:.32,priceProgressAtr:.05,evidence:["High volume without price progress"]}}});assert.notEqual(scenarios.highVolumeNoProgress.entryState,"TRIGGER ACTIVE");assert(scenarios.highVolumeNoProgress.comparisonDiagnostics.hardGates.failed.includes("effectiveFlow"));
  scenarios.weakParticipationCredibleAbsorption=evaluate({trigger:{flow:{effective:true,absorption:true,ineffectiveHighVolume:false,priceProgressAtr:.62,evidence:["Sell absorption resolved upward"]},participation:{state:"WEAK",score:58,credibleAbsorption:true,persistence:.7}}});assert.equal(scenarios.weakParticipationCredibleAbsorption.entryState,"TRIGGER ACTIVE");
  scenarios.reactionNoBreak=evaluate({trigger:{microstructureShift:false}});assert.equal(scenarios.reactionNoBreak.entryState,"TRIGGER FORMING");
  scenarios.controlledFollowThrough=evaluate({trigger:{retestHeld:false,qualifiedFollowThrough:true}});assert.equal(scenarios.controlledFollowThrough.entryState,"TRIGGER ACTIVE");
  scenarios.extremeWithoutAcceptance=evaluate({volatility:{regime:"Disorderly/extreme",controlledAcceptance:false}});assert(["TRIGGER FORMING","NO CHASE"].includes(scenarios.extremeWithoutAcceptance.entryState));
  scenarios.lateEntry=evaluate({current:{originDistanceAtr:1.8,chased:true}});assert.equal(scenarios.lateEntry.entryState,"NO CHASE");
  scenarios.primaryOpposition=evaluate({opposition:{effective:true,evidence:["5m sell pressure is effective"],neutral:false}});assert.notEqual(scenarios.primaryOpposition.entryState,"TRIGGER ACTIVE");
  scenarios.structuralInvalidation=evaluate({setup:{invalidated:true}});assert.equal(scenarios.structuralInvalidation.entryState,"SETUP FAILED");
  scenarios.staleData=evaluate({fresh:false});assert.notEqual(scenarios.staleData.entryState,"TRIGGER ACTIVE");
  scenarios.nonEmaStructural=evaluate({setup:{family:"Sweep and reclaim",nonEma:true}});assert.equal(scenarios.nonEmaStructural.entryState,"TRIGGER ACTIVE");
  scenarios.lowerTimeframeCounterMove=evaluate({lowerTimeframeWarning:{direction:"SHORT",effective:true}});assert.equal(scenarios.lowerTimeframeCounterMove.direction,"LONG");
  assert.equal(scenarios.cleanContinuation.setupQuality,"A");assert.equal(scenarios.cleanContinuation.triggerQuality,"A");assert.equal(scenarios.cleanContinuation.currentEntryQuality,"A");assert.equal(scenarios.cleanContinuation.comparisonDiagnostics.hardGates.failed.length,0);

  function directionalFacts(direction,{triggerLevel=100,target=direction==="LONG"?120:80,invalidation=direction==="LONG"?90:110,currentPrice=100,identity=`${direction}-geometry-${caseSequence+1}`,setupScore=85,interacted=true,reactionConfirmed=true,flowPatch={},triggerPatch={},currentPatch={},dataPatch={}}={}){
    return merge(baseFacts(),{
      directionalPermission:{permission:true,direction,score:75,longScore:direction==="LONG"?75:25,shortScore:direction==="SHORT"?75:25,reason:`${direction} alignment`,breakdown:{}},
      setup:{identity,family:"Structural retest",tf:"5m",direction,level:direction==="LONG"?96:104,zone:direction==="LONG"?{low:95,high:97}:{low:103,high:105},invalidation,target,interacted,reactionConfirmed,invalidated:false,repeatedTests:1,valid:true,nonEma:true},
      setupComponents:{structuralLocation:setupScore,regimeAlignment:setupScore,eventLevelQuality:setupScore,invalidationTargetGeometry:setupScore,volatilitySuitability:setupScore},
      trigger:{breakLevel:triggerLevel,...triggerPatch,flow:{effective:true,absorption:false,ineffectiveHighVolume:false,directionalImbalance:.18,priceProgressAtr:.72,directionalCloseShare:.75,efficiency:1.1,evidence:["Effective directional flow"],...flowPatch}},
      geometry:{target,targetTimeframe:"15m",feeSlippageAllowance:0},current:{price:currentPrice,originDistanceAtr:.2,chased:false,adverseEvidenceSafety:90,...currentPatch},data:{timeframesUsed:["1m","3m","5m","15m","1h","4h","1d"],freshness:"LIVE",...dataPatch}
    });
  }
  const validLong=engine.evaluateFacts(directionalFacts("LONG"),{horizonId:"quick",symbol:"BTCUSDT",directionMode:"LONG"});assert.equal(validLong.comparisonDiagnostics.setupGeometryValid,true);assert.equal(validLong.comparisonDiagnostics.viableNetRewardRisk,true);
  const longTargetBehind=engine.evaluateFacts(directionalFacts("LONG",{target:99,identity:"long-target-behind"}),{horizonId:"quick",symbol:"BTCUSDT",directionMode:"LONG"});assert.equal(longTargetBehind.entryState,"NO SETUP");assert.equal(longTargetBehind.comparisonDiagnostics.setupGeometryValid,false);assert.match(longTargetBehind.comparisonDiagnostics.finalStateReason,/target 99 is below required trigger 100/);
  const longInvalidationWrong=engine.evaluateFacts(directionalFacts("LONG",{invalidation:101,identity:"long-invalidation-wrong"}),{horizonId:"quick",symbol:"BTCUSDT",directionMode:"LONG"});assert.equal(longInvalidationWrong.comparisonDiagnostics.setupGeometryValid,false);assert.match(longInvalidationWrong.comparisonDiagnostics.finalStateReason,/invalidation 101 is above required trigger 100/);
  const validShort=engine.evaluateFacts(directionalFacts("SHORT"),{horizonId:"quick",symbol:"BTCUSDT",directionMode:"SHORT"});assert.equal(validShort.comparisonDiagnostics.setupGeometryValid,true);assert.equal(validShort.comparisonDiagnostics.viableNetRewardRisk,true);
  const shortTargetBehind=engine.evaluateFacts(directionalFacts("SHORT",{target:101,identity:"short-target-behind"}),{horizonId:"quick",symbol:"BTCUSDT",directionMode:"SHORT"});assert.equal(shortTargetBehind.comparisonDiagnostics.setupGeometryValid,false);assert.match(shortTargetBehind.comparisonDiagnostics.finalStateReason,/target 101 is above required trigger 100/);
  const shortInvalidationWrong=engine.evaluateFacts(directionalFacts("SHORT",{invalidation:99,identity:"short-invalidation-wrong"}),{horizonId:"quick",symbol:"BTCUSDT",directionMode:"SHORT"});assert.equal(shortInvalidationWrong.comparisonDiagnostics.setupGeometryValid,false);assert.match(shortInvalidationWrong.comparisonDiagnostics.finalStateReason,/invalidation 99 is below required trigger 100/);
  const triggerReference=engine.evaluateFacts(directionalFacts("LONG",{currentPrice:90,target:110,invalidation:95,identity:"trigger-reference"}),{horizonId:"quick",symbol:"BTCUSDT",directionMode:"LONG"});assert.equal(triggerReference.comparisonDiagnostics.remainingRewardRisk,2);assert.notEqual(triggerReference.comparisonDiagnostics.remainingRewardRisk,4);
  const lowQuality=engine.evaluateFacts(directionalFacts("LONG",{setupScore:58,identity:"low-quality-candidate"}),{horizonId:"quick",symbol:"BTCUSDT",directionMode:"LONG"});assert.equal(lowQuality.entryState,"WATCHING");assert.equal(lowQuality.comparisonDiagnostics.setupPresent,true);assert.equal(lowQuality.comparisonDiagnostics.setupQualityAcceptable,false);assert.equal(lowQuality.comparisonDiagnostics.validSetup,false);
  const standBy=engine.evaluateFacts(directionalFacts("LONG",{identity:"stand-by",reactionConfirmed:false,flowPatch:{effective:false,priceProgressAtr:0,directionalCloseShare:0,directionalImbalance:0},triggerPatch:{microstructureShift:false,displacementQuality:0,retestHeld:false,qualifiedFollowThrough:false,evidence:[]}}),{horizonId:"quick",symbol:"BTCUSDT",directionMode:"LONG"});assert.equal(standBy.entryState,"STAND BY");
  const weakened=engine.evaluateFacts(merge(directionalFacts("LONG",{identity:"weakened-setup"}),{setup:{repeatedTests:4}}),{horizonId:"quick",symbol:"BTCUSDT",directionMode:"LONG"});assert.equal(weakened.setupNotWeakened,false);assert(weakened.comparisonDiagnostics.hardGates.failed.includes("setupNotWeakened"));assert(!weakened.comparisonDiagnostics.hardGates.passed.includes("setupNotWeakened"));assert(weakened.comparisonDiagnostics.effectiveOppositionEvidence.some(value=>value.includes("weakened")));
  const lifecycleEngine=context.createSignalEngineB(),lifeFacts=directionalFacts("LONG",{identity:"lifecycle-old"}),lifeValid=lifecycleEngine.evaluateFacts(lifeFacts,{horizonId:"quick",symbol:"BTCUSDT",directionMode:"LONG",publicationGeneration:1});assert.equal(lifeValid.entryState,"TRIGGER ACTIVE");const lifeFailed=lifecycleEngine.evaluateFacts(merge(lifeFacts,{setup:{invalidated:true}}),{horizonId:"quick",symbol:"BTCUSDT",directionMode:"LONG",publicationGeneration:2});assert.equal(lifeFailed.entryState,"SETUP FAILED");const lifeReclaimed=lifecycleEngine.evaluateFacts(merge(lifeFacts,{setup:{invalidated:false}}),{horizonId:"quick",symbol:"BTCUSDT",directionMode:"LONG",publicationGeneration:3});assert.equal(lifeReclaimed.entryState,"SETUP FAILED");assert.equal(lifeReclaimed.setupIdentity,"lifecycle-old");const lifeNew=lifecycleEngine.evaluateFacts(directionalFacts("LONG",{identity:"lifecycle-new"}),{horizonId:"quick",symbol:"BTCUSDT",directionMode:"LONG",publicationGeneration:4});assert.equal(lifeNew.entryState,"TRIGGER ACTIVE");assert.equal(lifeNew.setupIdentity,"lifecycle-new");assert.equal(lifeNew.comparisonDiagnostics.publicationGeneration,4);
  const observedFacts={fresh:true,profile:{early:"1m",trigger:"3m",primary:"5m",setups:["3m","5m"],structures:["15m","1h"],boundaries:["4h","1d"],eventWindow:7,chaseAtr:1.35,minNetRr:1.35},directionalPermission:{permission:true,direction:"LONG",score:61,longScore:61,shortScore:39,reason:"LONG alignment 61%",breakdown:{lowerTimeframeWarning:"UNAVAILABLE"}},setup:{identity:"observed-long",family:"Structural retest",tf:"5m",direction:"LONG",level:64216.5,zone:{low:64209,high:64224},invalidation:64174,target:64249,interacted:true,reactionConfirmed:false,invalidated:false,repeatedTests:2,nonEma:true},setupComponents:{structuralLocation:58,regimeAlignment:58,eventLevelQuality:58,invalidationTargetGeometry:58,volatilitySuitability:58},trigger:{breakLevel:64282,microstructureShift:false,displacementQuality:0,wickHeavy:false,flow:{effective:false,absorption:false,ineffectiveHighVolume:true,directionalImbalance:.24,priceProgressAtr:-.63,directionalCloseShare:0,evidence:["Directional taker imbalance 24.0%","Resulting price progress -0.63 ATR","Directional closes 0%"]},participation:{state:"WEAK",score:46,credibleAbsorption:false,persistence:0},retestHeld:false,qualifiedFollowThrough:false,freshnessScore:0,evidence:["No closed 3m post-interaction structure shift"]},opposition:{effective:false,evidence:[],neutral:true},volatility:{regime:"Normal",controlledAcceptance:true,realizedRangePercentile:50},geometry:{target:64249,targetTimeframe:"15m",feeSlippageAllowance:0},current:{price:64227,originDistanceAtr:.1134,chased:false,adverseEvidenceSafety:100,volatilityParticipationPersistence:100},data:{timeframesUsed:["1m","3m","5m","15m","1h","4h","1d"],freshness:"LIVE",componentAvailability:{lowerTimeframeWarning:"UNAVAILABLE"}}},observed=engine.evaluateFacts(observedFacts,{horizonId:"quick",symbol:"BTCUSDT",version:7,directionMode:"LONG",publicationGeneration:17}),observedDiagnostics=observed.comparisonDiagnostics;
  assert.equal(observed.direction,"LONG");assert.equal(observed.confidence,61);assert.equal(observed.entryState,"NO SETUP");assert.equal(observed.setupPresent,true);assert.equal(observed.setupQualityAcceptable,false);assert.equal(observed.setupGeometryValid,false);assert.equal(observed.validSetup,false);assert.equal(observed.progressiveDisplacement,false);assert.equal(observed.viableNetRewardRisk,false);assert.equal(observed.estimatedNetRewardRisk,"INVALID");assert.equal(observedDiagnostics.setupPresent,true);assert.equal(observedDiagnostics.setupQualityAcceptable,false);assert.equal(observedDiagnostics.setupGeometryValid,false);assert.equal(observedDiagnostics.validSetup,false);assert.equal(observedDiagnostics.progressiveDisplacement,false);assert.equal(observedDiagnostics.viableNetRewardRisk,false);assert.equal(observedDiagnostics.remainingRewardRisk,"INVALID");assert.equal(Math.round(observedDiagnostics.setupScore),58);assert.equal(Math.round(observedDiagnostics.triggerScore),7);assert.equal(Math.round(observedDiagnostics.currentEntryScore),45);assert.equal(observedDiagnostics.finalStateReason,"No valid LONG setup: target 64,249 is below required trigger 64,282.");assert(observedDiagnostics.effectiveOppositionEvidence.some(value=>value.includes("-0.63 ATR against LONG")));assert(observedDiagnostics.effectiveOppositionEvidence.some(value=>value.includes("Directional closes 0%")));assert(observedDiagnostics.effectiveOppositionEvidence.some(value=>value.includes("Weak participation")));assert(observedDiagnostics.data.missing.includes("lowerTimeframeWarning"));
  const memberships=[...observedDiagnostics.hardGates.passed,...observedDiagnostics.hardGates.failed,...observedDiagnostics.hardGates.pending];assert.equal(new Set(memberships).size,memberships.length);assert(observedDiagnostics.hardGates.failed.includes("progressiveDisplacement"));assert(observedDiagnostics.hardGates.failed.includes("setupGeometryValid"));assert(!observedDiagnostics.hardGates.passed.includes("validSetup"));
  const observedTooltip=context.__PRESSURE_SIGNAL_FEATURE_BUILD__.createSignalDiagnosticsTooltip({...observed,engineId:"B",engineVersion:"1.1.0"},{mode:"LONG",evaluatedDirection:"LONG",direction:"LONG",visibleState:"NO SETUP",confidence:61,setupQuality:observed.setupQuality,triggerQuality:observed.triggerQuality,currentEntryQuality:observed.currentEntryQuality,publicationGeneration:17},"Quick");for(const section of ["HEADER","QUALITY","SETUP EVIDENCE","TRIGGER EVIDENCE","ENTRY CONDITION","DECISION","DATA"])assert(observedTooltip.includes(section));assert(observedTooltip.includes("Estimated net RR: INVALID"));assert(observedTooltip.includes("Missing or unavailable: net reward/risk; lowerTimeframeWarning"));assert(!observedTooltip.includes("Opposing evidence: NONE"));
  const frozenFacts=JSON.parse(JSON.stringify(observedFacts));(function freeze(value){if(value&&typeof value==="object"&&!Object.isFrozen(value)){Object.freeze(value);Object.values(value).forEach(freeze);}return value;})(frozenFacts);const frozenOne=context.createSignalEngineB().evaluateFacts(frozenFacts,{horizonId:"quick",symbol:"BTCUSDT",version:7,directionMode:"LONG",publicationGeneration:20}),frozenTwo=context.createSignalEngineB().evaluateFacts(frozenFacts,{horizonId:"quick",symbol:"BTCUSDT",version:7,directionMode:"LONG",publicationGeneration:20});assert.equal(JSON.stringify(frozenOne),JSON.stringify(frozenTwo));
  const manualLong=engine.evaluateFacts(directionalFacts("LONG",{identity:"manual-long"}),{horizonId:"quick",symbol:"BTCUSDT",directionMode:"LONG"}),manualShort=engine.evaluateFacts(directionalFacts("SHORT",{identity:"manual-short"}),{horizonId:"quick",symbol:"BTCUSDT",directionMode:"SHORT"});assert.equal(manualLong.direction,"LONG");assert.equal(manualShort.direction,"SHORT");

  // Production extraction smoke test uses fixed Signal-owned candle snapshots and no chart state.
  const timeframes=["1m","3m","5m","15m","1h","4h","1d"],closedByTf=Object.fromEntries(timeframes.map(tf=>[tf,rows(tf)])),snapshot={symbol:"BTCUSDT",horizonId:"quick",version:1,signature:"fixture-revision-1",currentPrice:closedByTf["1m"].at(-1).close,closedByTf,rowsByTf:closedByTf,maByTf:{},structureByTf:{},freshness:{signalStatus:"LIVE"},health:{status:"sufficient"}};
  const smoke=engine.evaluate({snapshot,horizonId:"quick",publicationGeneration:9});context.createSignalEngineRegistry().validateOutput(smoke);assert.equal(smoke.comparisonDiagnostics.engineVersion,"1.1.0");assert.equal(smoke.comparisonDiagnostics.publicationGeneration,9);
  const cached=engine.evaluate({snapshot,horizonId:"quick",publicationGeneration:9});assert.strictEqual(cached,smoke);assert.equal(engine.diagnostics().cacheHits,1);assert(engine.diagnostics().cacheCounts.evaluationCache<=24);

  // Requirements exactly follow the requested hierarchy and retain ordinary canonical MAs without specialized crossover forecasting.
  const plans={quick:engine.getRequirements({horizonId:"quick"}),two:engine.getRequirements({horizonId:"2_3h"}),six:engine.getRequirements({horizonId:"6_8h"})};
  assert.deepStrictEqual(JSON.parse(JSON.stringify(plans.quick.timeframes)),["1m","3m","5m","15m","1h","4h","1d"]);assert.deepStrictEqual(JSON.parse(JSON.stringify(plans.two.timeframes)),["3m","5m","15m","1h","4h","1d"]);assert.deepStrictEqual(JSON.parse(JSON.stringify(plans.six.timeframes)),["5m","15m","1h","4h","1d"]);
  const engineSource=fs.readFileSync(path.join(root,"features/pressure-signal/engines/engine-b.js"),"utf8");assert(!/VWAP/i.test(engineSource));assert(!/causes cross|probability forecast|15m-authoritative/i.test(engineSource));

  // A/B state, output, window selection, publication and Action isolation.
  const registry=context.createSignalEngineRegistry(),engineA=context.createSignalEngineA(),engineB=context.createSignalEngineB();registry.register(engineA);registry.register(engineB);registry.activate("A");
  assert.equal(registry.isAvailable("B"),true);assert.equal(registry.isAvailable("C"),false);assert.equal(registry.list().find(item=>item.id==="C").status,"unregistered");
  const aFixture={direction:"LONG",confidence:67,entryState:"WATCHING",setupIdentity:"a-setup",setupFamily:"MA21 bounce",setupTimeframe:"5m",setupQuality:"B",triggerQuality:"C",currentEntryQuality:"C",entryVerdict:"WAIT",reasons:["A reason"],exclusions:["A exclusion"],triggerIdentity:null,triggerEvidence:[],dataStatus:"sufficient",tone:"gray"};
  const aOutput=registry.evaluate({publicationGeneration:1,evaluateSignalA:()=>aFixture}),aBefore=JSON.stringify(aOutput),aStateBefore=engineA.diagnostics();registry.activate("B");const bOutput=registry.evaluate({publicationGeneration:2,snapshot,horizonId:"quick"});assert.equal(bOutput.engineId,"B");assert.equal(JSON.stringify(aOutput),aBefore);assert.deepStrictEqual(JSON.parse(JSON.stringify(engineA.diagnostics())),JSON.parse(JSON.stringify({...aStateBefore,deactivations:aStateBefore.deactivations+1,cacheCounts:{evidenceByTf:0,smcCache:0,entryTrackers:0,setupHistories:0,seenTriggerAlerts:0}})));
  const windowRegistryA=context.createSignalEngineRegistry(),windowRegistryB=context.createSignalEngineRegistry();for(const own of [windowRegistryA,windowRegistryB]){own.register(context.createSignalEngineA());own.register(context.createSignalEngineB());}
  const selectorA=context.createSignalEngineSelector({registry:windowRegistryA,storage:memoryStorage()}),selectorB=context.createSignalEngineSelector({registry:windowRegistryB,storage:memoryStorage()});selectorA.initialize();selectorB.initialize();selectorB.select("B");assert.equal(selectorA.getSelectedId(),"A");assert.equal(selectorB.getSelectedId(),"B");
  const source=fs.readFileSync(path.join(root,"features/pressure-signal/index.js"),"utf8"),windowsSource=fs.readFileSync(path.join(root,"features/pressure-signal/ui/windows.js"),"utf8"),html=fs.readFileSync(path.join(root,"index.html"),"utf8"),selectionBody=source.slice(source.indexOf("function onSignalEngineSelection37"),source.indexOf("signalEngineSelector=",source.indexOf("function onSignalEngineSelection37"))),action={text:"HOLD",tone:"green",fingerprint:"action-17",generation:17,managementHorizon:"quick",positionManagement:"ESTABLISHED"},actionBefore=JSON.stringify(action);
  assert(!/scheduleActionRefresh37|configureActionFeed37|invalidatePositionContext|setManagementHorizon/.test(selectionBody));selectorB.select("A");selectorB.select("B");assert.equal(JSON.stringify(action),actionBefore);
  assert(source.includes("signalEngineRegistry.accepts(output,{directionMode:state.direction,publicationGeneration:generation})"));assert(source.includes("engineId:output.engineId,signalId:output.signalId||output.engineId,engineVersion:output.engineVersion,directionMode:displayedSignal.mode,publicationGeneration:generation"));
  assert(source.includes('typeof window.createSignalEngineB==="function"')&&html.includes("features/pressure-signal/engines/engine-b.js"));assert(windowsSource.includes("Number(left.publicationGeneration)===Number(right.publicationGeneration)"));
  // Signal B's compact button text carries readinessScore as a plain number alongside a percent-free confidence,
  // e.g. "LONG 81 · TRIGGER FORMING · READY 65"; engines without a readinessScore keep the legacy "72%" wording.
  assert(source.includes("readinessScore:output.readinessScore"),"displayedFromEngineOutput37 must thread output.readinessScore into signalSummaryVariants37");
  assert(source.includes("READY ${Math.round(Number(readinessScore))}"),"compact button text must append a plain-number READY suffix when readinessScore is available");
  assert(source.includes("plainNumber:hasReadiness")&&source.includes("return plainNumber ? `${direction} ${Math.round(confidence)}` : `${direction} ${Math.round(confidence)}%`;"),"confidence must drop its % sign exactly when readinessScore is present");
  assert(!/setInterval|addEventListener|fetch\(|XMLHttpRequest|createPressureSignalDataFeed/.test(engineSource),"Signal B owns polling, listeners, REST, or sockets");
  for(const key of ["directionalPermissionScore","setupBreakdown","triggerBreakdown","currentEntryBreakdown","hardGates","effectiveOppositionEvidence","volatilityRegime","participationState","flowEffectiveness","chaseDistanceAtr","remainingRewardRisk","finalStateReason","engineVersion","publicationGeneration"])assert(Object.prototype.hasOwnProperty.call(scenarios.cleanContinuation.comparisonDiagnostics,key),`missing comparison diagnostic ${key}`);
  for(let index=0;index<40;index+=1){registry.activate("A",`leak-${index}-a`);registry.evaluate({publicationGeneration:index*2+3,evaluateSignalA:()=>aFixture});registry.activate("B",`leak-${index}-b`);registry.evaluate({publicationGeneration:index*2+4,snapshot:{...snapshot,signature:`fixture-switch-${index}`},horizonId:"quick"});}
  const lifecycle=registry.diagnostics();assert.equal(lifecycle.activeEvaluationCount,0);assert(engineB.diagnostics().cacheCounts.evaluationCache<=24);assert(source.includes("if(state.dataFeed) return state.dataFeed"));

  const result={passed:true,scenarios:Object.fromEntries(Object.entries(scenarios).map(([name,value])=>[name,{state:value.entryState,direction:value.direction,failedGates:value.comparisonDiagnostics.hardGates.failed}])),productionExtraction:true,requirements:true,signalAIsolation:true,perWindowIsolation:true,actionInvariance:true,cacheBounded:true};
  console.log("signal B tests: PASS",result);return result;
})();
module.exports=run;if(require.main===module)run.catch(error=>{console.error(error);process.exitCode=1;});
