-- SSSC-AUDIT-03: run manually in the Supabase SQL editor before deployment.
create table public.futures_market_snapshots (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  event_at timestamptz not null,
  machine_id text not null,
  symbol text not null,
  funding_rate numeric not null,
  open_interest numeric not null
);

create index futures_market_snapshots_machine_event_idx
  on public.futures_market_snapshots (machine_id, event_at desc);
