-- HEATMAP-BRIDGE-01: proposal only. Run manually after confirming this schema.
create table public.liquidation_heatmap_snapshots (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  event_at timestamptz not null,
  machine_id text not null,
  symbol text not null,
  duration text not null check (duration = '3D'),
  tick_size numeric not null check (tick_size > 0),
  chart_interval_seconds integer not null check (chart_interval_seconds > 0),
  cells jsonb not null check (jsonb_typeof(cells) = 'array'),
  metadata jsonb not null check (jsonb_typeof(metadata) = 'object'),
  provider_run_id text not null,
  provider_dataset_id text not null
);

create index liquidation_heatmap_snapshots_symbol_event_idx
  on public.liquidation_heatmap_snapshots (symbol, event_at desc);
