-- VMLOG-06: run manually in the Supabase SQL editor before deploying ma-stack-logger.
create table if not exists public.ma_stack_snapshots (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  event_at timestamptz not null,
  capture_id uuid not null,
  machine_id text not null,
  symbol text not null,
  timeframe text not null check (timeframe in ('1m','3m','5m','15m','30m','1h','4h','1d')),
  candle_open_at timestamptz not null,
  candle_close_at timestamptz,
  provisional boolean not null,
  available boolean not null,
  unavailable_reason text,
  state text not null,
  phase text,
  selected_regime text,
  setup_direction smallint check (setup_direction is null or setup_direction between -1 and 1),
  strength smallint check (strength is null or strength between 0 and 100),
  quality smallint check (quality is null or quality between 0 and 100),
  alignment_pct smallint check (alignment_pct is null or alignment_pct between 0 and 100),
  adx double precision,
  adx_shadow_5 double precision,
  led_ma1 boolean not null,
  led_ma2 boolean not null,
  led_ma3 boolean not null,
  led_ma4 boolean not null,
  led_ma5 boolean not null,
  led_match_count smallint check (led_match_count is null or led_match_count between 0 and 5),
  ma_periods jsonb not null,
  spread_pct double precision,
  spread_atr double precision,
  spread_score smallint check (spread_score is null or spread_score between 0 and 100),
  spread_label text,
  spread_condition text,
  ma_event_type text,
  ma_event_pair text,
  ma_event_pair_slots text,
  ma_event_pair_class text,
  ma_event_direction_raw smallint check (ma_event_direction_raw is null or ma_event_direction_raw between -1 and 1),
  ma_event_outcome_direction text,
  ma_event_age_candles smallint,
  ma_event_at timestamptz,
  ma_event_payload jsonb,
  engine_version text not null,
  schema_version smallint not null
);

create unique index if not exists ma_stack_snapshots_confirmed_candle_idx
  on public.ma_stack_snapshots (machine_id, symbol, timeframe, candle_open_at)
  where provisional = false;

create index if not exists ma_stack_snapshots_machine_symbol_tf_event_idx
  on public.ma_stack_snapshots (machine_id, symbol, timeframe, event_at desc);

create index if not exists ma_stack_snapshots_event_type_idx
  on public.ma_stack_snapshots (machine_id, symbol, timeframe, ma_event_type, event_at desc)
  where ma_event_type is not null;
