-- SCALP-V2-02: run once in the Supabase SQL editor before deploying the V2 logger.
create table if not exists public.scalp_v2_signals (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  machine_id text not null,
  symbol text not null,
  action text not null,
  source_timeframe text not null,
  detector_state jsonb not null,
  cascade_agreement jsonb not null,
  event_at timestamptz not null
);

create index if not exists scalp_v2_signals_machine_event_idx
  on public.scalp_v2_signals (machine_id, event_at desc);
