create table if not exists public.sig_b_snapshots (
  id bigint generated by default as identity primary key,
  event_at timestamptz not null,
  symbol text not null,
  machine_id text not null,
  direction text,
  entry_state text,
  confidence double precision,
  setup_score double precision,
  setup_breakdown jsonb not null default '{}'::jsonb,
  trigger_score double precision,
  trigger_breakdown jsonb not null default '{}'::jsonb,
  current_entry_score double precision,
  current_entry_breakdown jsonb not null default '{}'::jsonb,
  readiness_score double precision,
  readiness_breakdown jsonb not null default '{}'::jsonb,
  hard_gates jsonb not null default '{"passed":[],"failed":[],"pending":[]}'::jsonb,
  flow_effectiveness jsonb not null default '{}'::jsonb,
  chase_distance_atr double precision,
  chase_warning boolean not null default false,
  remaining_reward_risk text,
  reward_risk_status text,
  final_state_reason text,
  setup_identity text,
  setup_timeframe text,
  horizon_id text,
  publication_generation bigint,
  engine_version text,
  signal_output jsonb not null default '{}'::jsonb
);

create index if not exists sig_b_snapshots_event_at_idx
  on public.sig_b_snapshots (event_at desc);

create index if not exists sig_b_snapshots_machine_symbol_event_idx
  on public.sig_b_snapshots (machine_id, symbol, event_at desc);
