"use strict";
const assert=require("assert");
const fs=require("fs");
const path=require("path");
const vm=require("vm");
const core=require("./depth-profile-core.js");
const root=path.resolve(__dirname,"..","..");
const main=fs.readFileSync(path.join(root,"main.js"),"utf8");
const html=fs.readFileSync(path.join(root,"index.html"),"utf8");
const rf=fs.readFileSync(path.join(root,"features","rapid-fire","rapidFireModule.js"),"utf8");
const feature=fs.readFileSync(path.join(__dirname,"depth-profile.js"),"utf8");

const model=core.aggregate({price:100,bucketSize:10,depthRange:30,bids:[[99,2],[95,3],[89,4],[69,99]],asks:[[101,1],[109,2],[112,5],[131,99]]});
const buckets=Object.fromEntries(model.buckets.map(row=>[row.side+row.index,row]));
assert.equal(buckets.bid0.volume,5,"bid levels in one price bucket must sum into one bar");
assert.equal(buckets.bid1.volume,4);
assert.equal(buckets.ask0.volume,3,"ask levels in one price bucket must sum separately");
assert.equal(buckets.ask1.volume,5);
assert.equal(model.buckets.length,4,"there must be exactly one populated bar per side/bucket");
assert(!model.buckets.some(row=>row.volume===99),"levels outside the symmetric configured range must be excluded");
assert.equal(core.barLength(2,12),24);assert.equal(core.barLength(4,12),48,"bar length must be directly linear in raw resting volume");
assert.equal(core.opacity(2,2,8,.6),0,"volume at or below the zero-opacity threshold must be invisible");
assert.equal(core.opacity(5,2,8,.6),.3,"opacity must scale linearly between zero and full thresholds");
assert.equal(core.opacity(8,2,8,.6),.6);assert.equal(core.opacity(100,2,8,.6),.6,"overall layer opacity must cap individually full-opacity bars");
assert.equal(core.barLength(100,12,275),275,"maximum bar length must cap outlier buckets");
const activeDrawStart=main.indexOf("  draw = function(){",main.indexOf("p10InstallVolumeHandle"));
const activeDrawEnd=main.indexOf("  try{ if(typeof draw === 'function') draw();",activeDrawStart);
const activeDraw=main.slice(activeDrawStart,activeDrawEnd);
assert(activeDraw.includes("depthProfile.drawUnderlay({ctx,left,top,chartRight:w-right"),"Depth Profile must be wired into the active replacement renderer");
assert(activeDraw.indexOf("depthProfile.drawUnderlay")>activeDraw.indexOf("window.BT001HeatmapFeature.draw(ctx"),"Depth Profile must composite after the existing Liquidation Heatmap underlay");
assert(activeDraw.indexOf("depthProfile.drawUnderlay")<activeDraw.indexOf("for(let i=0;i<vis.length;i++){"),"Depth Profile must render before candles");
assert(main.includes('levelsSnapshot:bookPressureLevelsSnapshot')&&main.includes('subscribeDepth:subscribeBookPressureDepth'),"Depth Profile must reuse the synchronized Book Pressure deep feed");
assert(feature.includes('const REPAINT_MS=750')&&feature.includes('source.subscribeDepth(()=>scheduleRefresh(false))'),"depth data must stay real-time while visual model refreshes are throttled");
assert(feature.includes('bucket.side==="bid"?`rgba(0,168,61')&&feature.includes('`rgba(220,38,38'),"bar colors must be fixed green/red by book side only");
assert(feature.includes('DEFAULTS=Object.freeze({enabled:false,bucketSize:50,depthRange:400,zeroOpacityVolume:0,fullOpacityVolume:10,maxBarLength:600,layerOpacity:72})'),"all Depth Profile defaults must be explicit");
assert(feature.includes('button.textContent="OBD"')&&feature.includes('button.className="calc-module-orders-toggle depth-profile-overlay-toggle is-off"')&&feature.includes('controls.register(button,"obd")'),"OBD must use the shared chart overlay button treatment and registry");
assert(feature.includes('controls.register(book,"book")')&&feature.includes('String(button.textContent||"").trim().toLowerCase()==="book"'),"OBD placement must discover and register the existing Book control");
assert(feature.includes('className="calc-module-window depth-profile-settings-window hidden"')&&feature.includes('window.BT001FloatingWindow')&&feature.includes('modal.classList.add("hidden")'),"settings must use a standalone non-blocking floating window and dismiss the modal backdrop");
assert(feature.includes('id="depthProfileFullOpacityVolume" type="number" min="1" max="100000" step="1"')&&feature.includes('normalize:Math.round'),"full-opacity volume must be whole-number precision");
assert(feature.includes('current.zeroOpacityVolume,current.fullOpacityVolume,current.layerOpacity/100'),"draw opacity must combine both volume thresholds with the overall layer ceiling");
assert(feature.includes('Math.min(chartRight-left,current.maxBarLength)'),"draw length must honor the configured maximum");
assert(html.includes('depth-profile-core.js')&&html.includes('depth-profile.js'),"Depth Profile scripts must be loaded");
const featureWithoutExistingTabReference=feature.replace('get("heatmap")','get("existing-overlay-tab")');
assert(!featureWithoutExistingTabReference.toLowerCase().includes("heatmap")&&!html.includes("order-book-depth-heatmap"),"Depth Profile must not retain the retired heatmap naming outside the existing Liquidation Heatmap tab ID");
assert(rf.includes('id="rapidFireCollapse"')&&rf.includes('class="calc-module-body rapid-fire-body"')&&rf.includes('win.dataset.expandedHeight=Math.round(rect.height)+"px"')&&rf.includes('win.style.height=((head&&head.offsetHeight)||34)+"px"')&&rf.includes('if(win.dataset.expandedHeight)win.style.height=win.dataset.expandedHeight'),"RF must use the full Calc/GR save, collapse, and restore mechanism");
const collapseStart=rf.indexOf("function setCollapsed");
const collapseEnd=rf.indexOf("function resetDoubleArm",collapseStart);
const classes=new Set(),body={scrollTop:17},head={offsetHeight:28},attributes={};
const button={title:"Collapse",setAttribute:(name,value)=>{attributes[name]=value;}};
const win={dataset:{},style:{height:"284px",width:"500px"},classList:{contains:name=>classes.has(name),add:name=>classes.add(name),remove:name=>classes.delete(name)},getBoundingClientRect:()=>({width:500,height:284}),querySelector:selector=>selector===".rapid-fire-body"?body:null};
const collapseContext={q:id=>id==="rapidFireCollapse"?button:id==="rapidFireHead"?head:null,requestAnimationFrame:callback=>callback(),Number,Math};
vm.createContext(collapseContext);vm.runInContext(rf.slice(collapseStart,collapseEnd),collapseContext);
collapseContext.setCollapsed(win,true);
assert.equal(win.style.height,"28px");assert.equal(win.dataset.expandedHeight,"284px");assert(classes.has("is-collapsed"));assert.equal(attributes["aria-pressed"],"true");
body.scrollTop=0;collapseContext.setCollapsed(win,false);
assert.equal(win.style.height,"284px");assert.equal(win.style.width,"500px");assert.equal(body.scrollTop,17);assert(!classes.has("is-collapsed"));assert.equal(attributes["aria-pressed"],"false");
console.log("RF collapse and Depth Profile wiring tests passed.");
